<?$gyung="http://b1.interlife.co.kr/west/img/img2/"?>

<input type="hidden" name="taro_click" value="N">

<script language="JavaScript1.1">
gyung='<?=$gyung?>'

function F_checktaro(num_var){
	var taro_check = document.getElementById("taro_click");
	var taro_tt = document.getElementById("tt");
	
	if (taro_tt.value == ''){
		alert('소원을 적으신 후 카드를 선택해주세요.'); return;
	}else{
		taro_check.value = 'Y';

		switch (num_var)
		{
			case "image_1" : image_1(); break;
			case "image_2" : image_2(); break;
			case "image_3" : image_3(); break;
			case "image_4" : image_4(); break;
			case "image_5" : image_5(); break;
			case "image_6" : image_6(); break;
			case "image_7" : image_7(); break;
			case "image_8" : image_8(); break;
			case "image_9" : image_9(); break;
			case "image_10" : image_10(); break;
			case "image_11" : image_11(); break;
			case "image_12" : image_12(); break;
			case "image_13" : image_13(); break;
			case "image_14" : image_14(); break;
			case "image_15" : image_15(); break;
			case "image_16" : image_16(); break;
			case "image_17" : image_17(); break;
			case "image_18" : image_18(); break;
			case "image_19" : image_19(); break;
			case "image_20" : image_20(); break;
			case "image_21" : image_21(); break;
			case "image_22" : image_22(); break;
		}
	}
}

function image_1(){
		document.images.Image66.src=gyung+"taro_2/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}
function image_2(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_2/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_3(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_2/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_4(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_2/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_5(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_2/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_6(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_2/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_7(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_2/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_8(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_2/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_9(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_2/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_10(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_2/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_11(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_2/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_12(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_2/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_13(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_2/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_14(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_2/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_15(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_2/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_16(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_2/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_17(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_2/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_18(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_2/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_19(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_2/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_20(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_2/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_21(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_2/2.gif"
		document.images.Image87.src=gyung+"taro_1/22.gif"
}function image_22(){
		document.images.Image66.src=gyung+"taro_1/1.gif"
		document.images.Image67.src=gyung+"taro_1/2.gif"
		document.images.Image68.src=gyung+"taro_1/2.gif"
		document.images.Image69.src=gyung+"taro_1/2.gif"
		document.images.Image70.src=gyung+"taro_1/2.gif"
		document.images.Image71.src=gyung+"taro_1/2.gif"
		document.images.Image72.src=gyung+"taro_1/2.gif"
		document.images.Image73.src=gyung+"taro_1/2.gif"
		document.images.Image74.src=gyung+"taro_1/2.gif"
		document.images.Image75.src=gyung+"taro_1/2.gif"
		document.images.Image76.src=gyung+"taro_1/2.gif"
		document.images.Image77.src=gyung+"taro_1/2.gif"
		document.images.Image78.src=gyung+"taro_1/2.gif"
		document.images.Image79.src=gyung+"taro_1/2.gif"
		document.images.Image80.src=gyung+"taro_1/2.gif"
		document.images.Image81.src=gyung+"taro_1/2.gif"
		document.images.Image82.src=gyung+"taro_1/2.gif"
		document.images.Image83.src=gyung+"taro_1/2.gif"
		document.images.Image84.src=gyung+"taro_1/2.gif"
		document.images.Image85.src=gyung+"taro_1/2.gif"
		document.images.Image86.src=gyung+"taro_1/2.gif"
		document.images.Image87.src=gyung+"taro_2/22.gif"
}
</Script>  
<table width="361" height="68" border="0" cellpadding="0" cellspacing="0" align="center">
					
						<TR>
							<TD colspan=22 align="center"><INPUT TYPE="text" NAME="tt" size="50" maxlength="50"><BR><BR></TD>
						</TR>
				
                        <tr> 
                          <td width="1"><a onclick="javascript:F_checktaro('image_22')" style="cursor:hand"><img src="<?=$gyung?>taro_1/22.gif" name="Image87" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_21')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image86" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_20')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image85" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_19')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image84" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_18')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image83" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_17')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image82" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_16')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image81" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_15')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image80" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_14')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image79" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_13')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image78" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_12')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image77" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_11')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image76" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_10')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image75" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_9')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image74" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_8')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image73" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_7')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image72" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_6')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image71" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_5')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image70" width="15" height="112" border="0"></a></td>
                          <td width="1"><a onclick="javascript:F_checktaro('image_4')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image69" width="15" height="112" border="0"></a></td>
                          <td width="189"><a onclick="javascript:F_checktaro('image_3')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image68" width="14" height="112" border="0"></a></td>
                          <td width="49"><a onclick="javascript:F_checktaro('image_2')" style="cursor:hand"><img src="<?=$gyung?>taro_1/2.gif" name="Image67" width="15" height="112" border="0"></a></td>
                          <td width="104"><a onclick="javascript:F_checktaro('image_1')" style="cursor:hand"><img src="<?=$gyung?>taro_1/1.gif" name="Image66" width="84" height="112" border="0"></a></td>
                        </tr>
                      </table>
					  <br>