<?
if ((($my_year_e_org == '11')&&($my_month_e_org == '01'))||(($my_year_e_org == '12')&&($my_month_e_org == '02'))||(($my_year_e_org == '01')&&($my_month_e_org == '03'))||(($my_year_e_org == '02')&&($my_month_e_org == '04'))||(($my_year_e_org == '03')&&($my_month_e_org == '05'))||(($my_year_e_org == '04')&&($my_month_e_org == '06'))||(($my_year_e_org == '05')&&($my_month_e_org == '07'))||(($my_year_e_org == '06')&&($my_month_e_org == '08'))||(($my_year_e_org == '07')&&($my_month_e_org == '09'))||(($my_year_e_org == '08')&&($my_month_e_org == '10'))||(($my_year_e_org == '09')&&($my_month_e_org == '11'))||(($my_year_e_org == '10')&&($my_month_e_org == '12'))) {$total_11 = '11';}
if ((($my_year_e_org == '11')&&($my_month_e_org == '02'))||(($my_year_e_org == '12')&&($my_month_e_org == '03'))||(($my_year_e_org == '01')&&($my_month_e_org == '04'))||(($my_year_e_org == '02')&&($my_month_e_org == '05'))||(($my_year_e_org == '03')&&($my_month_e_org == '06'))||(($my_year_e_org == '04')&&($my_month_e_org == '07'))||(($my_year_e_org == '05')&&($my_month_e_org == '08'))||(($my_year_e_org == '06')&&($my_month_e_org == '09'))||(($my_year_e_org == '07')&&($my_month_e_org == '10'))||(($my_year_e_org == '08')&&($my_month_e_org == '11'))||(($my_year_e_org == '09')&&($my_month_e_org == '12'))||(($my_year_e_org == '10')&&($my_month_e_org == '01'))) {$total_11 = '12';}
if ((($my_year_e_org == '11')&&($my_month_e_org == '03'))||(($my_year_e_org == '12')&&($my_month_e_org == '04'))||(($my_year_e_org == '01')&&($my_month_e_org == '05'))||(($my_year_e_org == '02')&&($my_month_e_org == '06'))||(($my_year_e_org == '03')&&($my_month_e_org == '07'))||(($my_year_e_org == '04')&&($my_month_e_org == '08'))||(($my_year_e_org == '05')&&($my_month_e_org == '09'))||(($my_year_e_org == '06')&&($my_month_e_org == '10'))||(($my_year_e_org == '07')&&($my_month_e_org == '11'))||(($my_year_e_org == '08')&&($my_month_e_org == '12'))||(($my_year_e_org == '09')&&($my_month_e_org == '01'))||(($my_year_e_org == '10')&&($my_month_e_org == '02'))) {$total_11 = '01';}
if ((($my_year_e_org == '11')&&($my_month_e_org == '04'))||(($my_year_e_org == '12')&&($my_month_e_org == '05'))||(($my_year_e_org == '01')&&($my_month_e_org == '06'))||(($my_year_e_org == '02')&&($my_month_e_org == '07'))||(($my_year_e_org == '03')&&($my_month_e_org == '08'))||(($my_year_e_org == '04')&&($my_month_e_org == '09'))||(($my_year_e_org == '05')&&($my_month_e_org == '10'))||(($my_year_e_org == '06')&&($my_month_e_org == '11'))||(($my_year_e_org == '07')&&($my_month_e_org == '12'))||(($my_year_e_org == '08')&&($my_month_e_org == '01'))||(($my_year_e_org == '09')&&($my_month_e_org == '02'))||(($my_year_e_org == '10')&&($my_month_e_org == '03'))) {$total_11 = '02';}
if ((($my_year_e_org == '11')&&($my_month_e_org == '05'))||(($my_year_e_org == '12')&&($my_month_e_org == '06'))||(($my_year_e_org == '01')&&($my_month_e_org == '07'))||(($my_year_e_org == '02')&&($my_month_e_org == '08'))||(($my_year_e_org == '03')&&($my_month_e_org == '09'))||(($my_year_e_org == '04')&&($my_month_e_org == '10'))||(($my_year_e_org == '05')&&($my_month_e_org == '11'))||(($my_year_e_org == '06')&&($my_month_e_org == '12'))||(($my_year_e_org == '07')&&($my_month_e_org == '01'))||(($my_year_e_org == '08')&&($my_month_e_org == '02'))||(($my_year_e_org == '09')&&($my_month_e_org == '03'))||(($my_year_e_org == '10')&&($my_month_e_org == '04'))) {$total_11 = '03';}
if ((($my_year_e_org == '11')&&($my_month_e_org == '06'))||(($my_year_e_org == '12')&&($my_month_e_org == '07'))||(($my_year_e_org == '01')&&($my_month_e_org == '08'))||(($my_year_e_org == '02')&&($my_month_e_org == '09'))||(($my_year_e_org == '03')&&($my_month_e_org == '10'))||(($my_year_e_org == '04')&&($my_month_e_org == '11'))||(($my_year_e_org == '05')&&($my_month_e_org == '12'))||(($my_year_e_org == '06')&&($my_month_e_org == '01'))||(($my_year_e_org == '07')&&($my_month_e_org == '02'))||(($my_year_e_org == '08')&&($my_month_e_org == '03'))||(($my_year_e_org == '09')&&($my_month_e_org == '04'))||(($my_year_e_org == '10')&&($my_month_e_org == '05'))) {$total_11 = '04';}
if ((($my_year_e_org == '11')&&($my_month_e_org == '07'))||(($my_year_e_org == '12')&&($my_month_e_org == '08'))||(($my_year_e_org == '01')&&($my_month_e_org == '09'))||(($my_year_e_org == '02')&&($my_month_e_org == '10'))||(($my_year_e_org == '03')&&($my_month_e_org == '11'))||(($my_year_e_org == '04')&&($my_month_e_org == '12'))||(($my_year_e_org == '05')&&($my_month_e_org == '01'))||(($my_year_e_org == '06')&&($my_month_e_org == '02'))||(($my_year_e_org == '07')&&($my_month_e_org == '03'))||(($my_year_e_org == '08')&&($my_month_e_org == '04'))||(($my_year_e_org == '09')&&($my_month_e_org == '05'))||(($my_year_e_org == '10')&&($my_month_e_org == '06'))) {$total_11 = '05';}
if ((($my_year_e_org == '11')&&($my_month_e_org == '08'))||(($my_year_e_org == '12')&&($my_month_e_org == '09'))||(($my_year_e_org == '01')&&($my_month_e_org == '10'))||(($my_year_e_org == '02')&&($my_month_e_org == '11'))||(($my_year_e_org == '03')&&($my_month_e_org == '12'))||(($my_year_e_org == '04')&&($my_month_e_org == '01'))||(($my_year_e_org == '05')&&($my_month_e_org == '02'))||(($my_year_e_org == '06')&&($my_month_e_org == '03'))||(($my_year_e_org == '07')&&($my_month_e_org == '04'))||(($my_year_e_org == '08')&&($my_month_e_org == '05'))||(($my_year_e_org == '09')&&($my_month_e_org == '06'))||(($my_year_e_org == '10')&&($my_month_e_org == '07'))) {$total_11 = '06';}
if ((($my_year_e_org == '11')&&($my_month_e_org == '09'))||(($my_year_e_org == '12')&&($my_month_e_org == '10'))||(($my_year_e_org == '01')&&($my_month_e_org == '11'))||(($my_year_e_org == '02')&&($my_month_e_org == '12'))||(($my_year_e_org == '03')&&($my_month_e_org == '01'))||(($my_year_e_org == '04')&&($my_month_e_org == '02'))||(($my_year_e_org == '05')&&($my_month_e_org == '03'))||(($my_year_e_org == '06')&&($my_month_e_org == '04'))||(($my_year_e_org == '07')&&($my_month_e_org == '05'))||(($my_year_e_org == '08')&&($my_month_e_org == '06'))||(($my_year_e_org == '09')&&($my_month_e_org == '07'))||(($my_year_e_org == '10')&&($my_month_e_org == '08'))) {$total_11 = '07';}
if ((($my_year_e_org == '11')&&($my_month_e_org == '10'))||(($my_year_e_org == '12')&&($my_month_e_org == '11'))||(($my_year_e_org == '01')&&($my_month_e_org == '12'))||(($my_year_e_org == '02')&&($my_month_e_org == '01'))||(($my_year_e_org == '03')&&($my_month_e_org == '02'))||(($my_year_e_org == '04')&&($my_month_e_org == '03'))||(($my_year_e_org == '05')&&($my_month_e_org == '04'))||(($my_year_e_org == '06')&&($my_month_e_org == '05'))||(($my_year_e_org == '07')&&($my_month_e_org == '06'))||(($my_year_e_org == '08')&&($my_month_e_org == '07'))||(($my_year_e_org == '09')&&($my_month_e_org == '08'))||(($my_year_e_org == '10')&&($my_month_e_org == '09'))) {$total_11 = '08';}
if ((($my_year_e_org == '11')&&($my_month_e_org == '11'))||(($my_year_e_org == '12')&&($my_month_e_org == '12'))||(($my_year_e_org == '01')&&($my_month_e_org == '01'))||(($my_year_e_org == '02')&&($my_month_e_org == '02'))||(($my_year_e_org == '03')&&($my_month_e_org == '03'))||(($my_year_e_org == '04')&&($my_month_e_org == '04'))||(($my_year_e_org == '05')&&($my_month_e_org == '05'))||(($my_year_e_org == '06')&&($my_month_e_org == '06'))||(($my_year_e_org == '07')&&($my_month_e_org == '07'))||(($my_year_e_org == '08')&&($my_month_e_org == '08'))||(($my_year_e_org == '09')&&($my_month_e_org == '09'))||(($my_year_e_org == '10')&&($my_month_e_org == '10'))) {$total_11 = '09';}
if ((($my_year_e_org == '11')&&($my_month_e_org == '12'))||(($my_year_e_org == '12')&&($my_month_e_org == '01'))||(($my_year_e_org == '01')&&($my_month_e_org == '02'))||(($my_year_e_org == '02')&&($my_month_e_org == '03'))||(($my_year_e_org == '03')&&($my_month_e_org == '04'))||(($my_year_e_org == '04')&&($my_month_e_org == '05'))||(($my_year_e_org == '05')&&($my_month_e_org == '06'))||(($my_year_e_org == '06')&&($my_month_e_org == '07'))||(($my_year_e_org == '07')&&($my_month_e_org == '08'))||(($my_year_e_org == '08')&&($my_month_e_org == '09'))||(($my_year_e_org == '09')&&($my_month_e_org == '10'))||(($my_year_e_org == '10')&&($my_month_e_org == '11'))) {$total_11 = '10';}


if($sex == "남"){
	$choie_data = "DB_data_m";
}Else{
	$choie_data = "DB_data_w";
}
	$choie_data = "DB_data_1";

$sql = "SELECT ".$choie_data." as result_var, DB_numerical FROM S061 WHERE DB_express = '".$total_11."'";
if (!$sql) {
   error("QUERY_ERROR");
}

$query = mysql_query($sql);
$all = mysql_affected_rows();

if (!$all) {
  error("QUERY_ERROR");
}

		for ($i = 0 ; $i<$all; $i++) {
			mysql_data_seek($query,$i);
			$row = mysql_fetch_array($query);
			 			
			$Tb_S061 = stripslashes($row[result_var]);
			$Tb_S061_numerical = stripslashes($row[DB_numerical]);          		
		
			}
?>