
<?
include "../../etc/S126_sal_data.php";

function S_response_write($var_str){
	If($var_str != ""){echo $var_str ."<BR><BR>";}
}

?>

<?S_response_write($sal_y_data)?>
<?S_response_write($cheneul_y_data)?>
<?S_response_write($chenbok_y_data)?>
<?S_response_write($chenguan_y_data)?>
<?S_response_write($chenju_y_data)?>
<?S_response_write($wolduk_y_data)?>
<?S_response_write($taeguk_y_data)?>
<?S_response_write($guangui_y_data)?>
<?S_response_write($munchang_y_data)?>
<?S_response_write($mungok_y_data)?>
<?S_response_write($amrok_y_data)?>
<?S_response_write($gumrok_y_data)?>
<?S_response_write($hakdang_y_data)?>
<?S_response_write($chene_y_data)?>
<?S_response_write($guegangsal_y_data)?>
<?S_response_write($bekhosal_y_data)?>
<?S_response_write($wonjinsal_y_data)?>
<?S_response_write($guimunsal_y_data)?>
<?S_response_write($hongsal_y_data)?>
<?S_response_write($yanginsal_y_data)?>
<?S_response_write($gongmangsal_y_data)?>
<?S_response_write($sangmunsal_y_data)?>
<?S_response_write($suoksal_y_data)?>
<?S_response_write($gepgaksal_y_data)?>
<?S_response_write($hyosinsal_y_data)?>
<?S_response_write($jinsin_y_data)?>
<?S_response_write($pengdu_y_data)?>
<?S_response_write($chumyung_y_data)?>
<?S_response_write($boksung_y_data)?>
<?S_response_write($gumsin_y_data)?>
<?S_response_write($yeayeon_y_data)?>
<?S_response_write($gokgak_y_data)?>
<?S_response_write($ilduk_y_data)?>
<?S_response_write($yeche_y_data)?>
<?S_response_write($yebu_y_data)?>
<?S_response_write($ganjidong_y_data)?>
<?S_response_write($umin_y_data)?>
<?S_response_write($sindese_y_data)?>
<?S_response_write($chenil_y_data)?>
<?S_response_write($gebi_y_data)?>
<?S_response_write($nak_y_data)?>
<?S_response_write($jego_y_data)?>
<?S_response_write($namyen_y_data)?>
<?S_response_write($noegan_y_data)?>
<?S_response_write($chul_y_data)?>
<?S_response_write($guansik_y_data)?>
<?S_response_write($hchim_y_data)?>
<?S_response_write($gyosin_y_data)?>
<?S_response_write($yangchak_y_data)?>
<?S_response_write($umcha_y_data)?>
<?S_response_write($biin_y_data)?>
<?S_response_write($toesin_y_data)?>
<?S_response_write($chilsal_y_data)?>
<?S_response_write($boksin_y_data)?>
<?S_response_write($chelsa_y_data)?>
<?S_response_write($guchu_y_data)?>
<?S_response_write($danjang_y_data)?>
<?S_response_write($uha_y_data)?>
<?S_response_write($chela_y_data)?>
<?S_response_write($yuksu_y_data)?>
<?S_response_write($umyok_y_data)?>
<?S_response_write($sangsa_y_data)?>
<?S_response_write($sangyok_y_data)?>
<?S_response_write($janggun_y_data)?>
<?S_response_write($jungrok_y_data)?>
<?S_response_write($sal_m_data)?>
<?S_response_write($cheneul_m_data)?>
<?S_response_write($chenbok_m_data)?>
<?S_response_write($chenguan_m_data)?>
<?S_response_write($chenju_m_data)?>
<?S_response_write($wolduk_m_data)?>
<?S_response_write($taeguk_m_data)?>
<?S_response_write($guangui_m_data)?>
<?S_response_write($munchang_m_data)?>
<?S_response_write($mungok_m_data)?>
<?S_response_write($amrok_m_data)?>
<?S_response_write($gumrok_m_data)?>
<?S_response_write($hakdang_m_data)?>
<?S_response_write($chene_m_data)?>
<?S_response_write($guegangsal_m_data)?>
<?S_response_write($bekhosal_m_data)?>
<?S_response_write($wonjinsal_m_data)?>
<?S_response_write($guimunsal_m_data)?>
<?S_response_write($hongsal_m_data)?>
<?S_response_write($yanginsal_m_data)?>
<?S_response_write($gongmangsal_m_data)?>
<?S_response_write($sangmunsal_m_data)?>
<?S_response_write($suoksal_m_data)?>
<?S_response_write($gepgaksal_m_data)?>
<?S_response_write($gosinsal_m_data)?>
<?S_response_write($guasuksal_m_data)?>
<?S_response_write($hyosinsal_m_data)?>
<?S_response_write($jinsin_m_data)?>
<?S_response_write($pengdu_m_data)?>
<?S_response_write($chumyung_m_data)?>
<?S_response_write($boksung_m_data)?>
<?S_response_write($gumsin_m_data)?>
<?S_response_write($yeayeon_m_data)?>
<?S_response_write($gokgak_m_data)?>
<?S_response_write($ilduk_m_data)?>
<?S_response_write($yeche_m_data)?>
<?S_response_write($yebu_m_data)?>
<?S_response_write($ganjidong_m_data)?>
<?S_response_write($umin_m_data)?>
<?S_response_write($sindese_m_data)?>
<?S_response_write($chenil_m_data)?>
<?S_response_write($gebi_m_data)?>
<?S_response_write($nak_m_data)?>
<?S_response_write($jego_m_data)?>
<?S_response_write($namyen_m_data)?>
<?S_response_write($noegan_m_data)?>
<?S_response_write($chul_m_data)?>
<?S_response_write($guansik_m_data)?>
<?S_response_write($hchim_m_data)?>
<?S_response_write($gyosin_m_data)?>
<?S_response_write($yangchak_m_data)?>
<?S_response_write($umcha_m_data)?>
<?S_response_write($biin_m_data)?>
<?S_response_write($toesin_m_data)?>
<?S_response_write($chilsal_m_data)?>
<?S_response_write($boksin_m_data)?>
<?S_response_write($chelsa_m_data)?>
<?S_response_write($guchu_m_data)?>
<?S_response_write($danjang_m_data)?>
<?S_response_write($uha_m_data)?>
<?S_response_write($chela_m_data)?>
<?S_response_write($yuksu_m_data)?>
<?S_response_write($umyok_m_data)?>
<?S_response_write($sangsa_m_data)?>
<?S_response_write($sangyok_m_data)?>
<?S_response_write($janggun_m_data)?>
<?S_response_write($jungrok_m_data)?>
<?S_response_write($sal_d_data)?>
<?S_response_write($cheneul_d_data)?>
<?S_response_write($chenbok_d_data)?>
<?S_response_write($chenguan_d_data)?>
<?S_response_write($chenju_d_data)?>
<?S_response_write($wolduk_d_data)?>
<?S_response_write($taeguk_d_data)?>
<?S_response_write($guangui_d_data)?>
<?S_response_write($munchang_d_data)?>
<?S_response_write($mungok_d_data)?>
<?S_response_write($amrok_d_data)?>
<?S_response_write($gumrok_d_data)?>
<?S_response_write($hakdang_d_data)?>
<?S_response_write($chene_d_data)?>
<?S_response_write($guegangsal_d_data)?>
<?S_response_write($bekhosal_d_data)?>
<?S_response_write($wonjinsal_d_data)?>
<?S_response_write($guimunsal_d_data)?>
<?S_response_write($hongsal_d_data)?>
<?S_response_write($yanginsal_d_data)?>
<?S_response_write($gongmangsal_d_data)?>
<?S_response_write($sangmunsal_d_data)?>
<?S_response_write($suoksal_d_data)?>
<?S_response_write($gepgaksal_d_data)?>
<?S_response_write($hyosinsal_d_data)?>
<?S_response_write($jinsin_d_data)?>
<?S_response_write($pengdu_d_data)?>
<?S_response_write($chumyung_d_data)?>
<?S_response_write($boksung_d_data)?>
<?S_response_write($gumsin_d_data)?>
<?S_response_write($yeayeon_d_data)?>
<?S_response_write($gokgak_d_data)?>
<?S_response_write($ilduk_d_data)?>
<?S_response_write($yeche_d_data)?>
<?S_response_write($yebu_d_data)?>
<?S_response_write($ganjidong_d_data)?>
<?S_response_write($umin_d_data)?>
<?S_response_write($sindese_d_data)?>
<?S_response_write($chenil_d_data)?>
<?S_response_write($gebi_d_data)?>
<?S_response_write($nak_d_data)?>
<?S_response_write($jego_d_data)?>
<?S_response_write($namyen_d_data)?>
<?S_response_write($noegan_d_data)?>
<?S_response_write($chul_d_data)?>
<?S_response_write($guansik_d_data)?>
<?S_response_write($hchim_d_data)?>
<?S_response_write($gyosin_d_data)?>
<?S_response_write($yangchak_d_data)?>
<?S_response_write($umcha_d_data)?>
<?S_response_write($umyang_d_data)?>
<?S_response_write($biin_d_data)?>
<?S_response_write($toesin_d_data)?>
<?S_response_write($chilsal_d_data)?>
<?S_response_write($boksin_d_data)?>
<?S_response_write($chelsa_d_data)?>
<?S_response_write($guchu_d_data)?>
<?S_response_write($danjang_d_data)?>
<?S_response_write($uha_d_data)?>
<?S_response_write($chela_d_data)?>
<?S_response_write($yuksu_d_data)?>
<?S_response_write($umyok_d_data)?>
<?S_response_write($sangsa_d_data)?>
<?S_response_write($sangyok_d_data)?>
<?S_response_write($janggun_d_data)?>
<?S_response_write($jungrok_d_data)?>
<?S_response_write($sal_h_data)?>
<?S_response_write($cheneul_h_data)?>
<?S_response_write($chenbok_h_data)?>
<?S_response_write($chenguan_h_data)?>
<?S_response_write($chenju_h_data)?>
<?S_response_write($wolduk_h_data)?>
<?S_response_write($taeguk_h_data)?>
<?S_response_write($guangui_h_data)?>
<?S_response_write($munchang_h_data)?>
<?S_response_write($mungok_h_data)?>
<?S_response_write($amrok_h_data)?>
<?S_response_write($hakdang_h_data)?>
<?S_response_write($chene_h_data)?>
<?S_response_write($guegangsal_h_data)?>
<?S_response_write($bekhosal_h_data)?>
<?S_response_write($wonjinsal_h_data)?>
<?S_response_write($guimunsal_h_data)?>
<?S_response_write($hongsal_h_data)?>
<?S_response_write($yanginsal_h_data)?>
<?S_response_write($gongmangsal_h_data)?>
<?S_response_write($sangmunsal_h_data)?>
<?S_response_write($suoksal_h_data)?>
<?S_response_write($gepgaksal_h_data)?>
<?S_response_write($hyosinsal_h_data)?>
<?S_response_write($jinsin_h_data)?>
<?S_response_write($pengdu_h_data)?>
<?S_response_write($chumyung_h_data)?>
<?S_response_write($boksung_h_data)?>
<?S_response_write($gumsin_h_data)?>
<?S_response_write($yeayeon_h_data)?>
<?S_response_write($gokgak_h_data)?>
<?S_response_write($ilduk_h_data)?>
<?S_response_write($yeche_h_data)?>
<?S_response_write($yebu_h_data)?>
<?S_response_write($ganjidong_h_data)?>
<?S_response_write($umin_h_data)?>
<?S_response_write($sindese_h_data)?>
<?S_response_write($chenil_h_data)?>
<?S_response_write($gebi_h_data)?>
<?S_response_write($nak_h_data)?>
<?S_response_write($jego_h_data)?>
<?S_response_write($namyen_h_data)?>
<?S_response_write($noegan_h_data)?>
<?S_response_write($chul_h_data)?>
<?S_response_write($guansik_h_data)?>
<?S_response_write($hchim_h_data)?>
<?S_response_write($gyosin_h_data)?>
<?S_response_write($yangchak_h_data)?>
<?S_response_write($umcha_h_data)?>
<?S_response_write($biin_h_data)?>
<?S_response_write($toesin_h_data)?>
<?S_response_write($chilsal_h_data)?>
<?S_response_write($boksin_h_data)?>
<?S_response_write($chelsa_h_data)?>
<?S_response_write($guchu_h_data)?>
<?S_response_write($danjang_h_data)?>
<?S_response_write($uha_h_data)?>
<?S_response_write($chela_h_data)?>
<?S_response_write($yuksu_h_data)?>
<?S_response_write($umyok_h_data)?>
<?S_response_write($sangsa_h_data)?>
<?S_response_write($sangyok_h_data)?>
<?S_response_write($janggun_h_data)?>
<?S_response_write($jungrok_h_data)?>
<?S_response_write($dowhasal_data)?>
<?S_response_write($gubsal_disp)?>
<?S_response_write($jaesal_disp)?>
<?S_response_write($cheunsal_disp)?>
<?S_response_write($jisal_disp)?>
<?S_response_write($yeunsal_disp)?>
<?S_response_write($wolsal_disp)?>
<?S_response_write($mangsinsal_disp)?>
<?S_response_write($jangsungsal_disp)?>
<?S_response_write($banansal_disp)?>	
<?S_response_write($masal_disp)?>
<?S_response_write($yukhaesal_disp)?>
<?S_response_write($whagaesal_disp)?>
<?S_response_write($sangmun_disp)?>
<?S_response_write($jogeak_disp)?>
<?S_response_write($gosin_disp)?>
<?S_response_write($guasuk_disp)?>
<?S_response_write($chenmo_disp)?>
<?S_response_write($jimo_disp)?>
<?S_response_write($daemo_disp)?>
<?S_response_write($somo_disp)?>
<?S_response_write($geuk_disp)?>
<?S_response_write($banum_disp)?>
<?S_response_write($bokum_disp)?>
<?S_response_write($bengbu_disp)?>
<?S_response_write($sabu_disp)?>
<?S_response_write($guanbu_disp)?>
<?S_response_write($taeum_disp)?>
<?S_response_write($sepa_disp)?>
<?S_response_write($byem_disp)?>
<?S_response_write($tang_disp)?>
<?S_response_write($samjae1_disp)?>
<?S_response_write($samjae2_disp)?>
<?S_response_write($samjae3_disp)?>
<?S_response_write($dan_disp)?>
<?S_response_write($uha_disp)?>
<?S_response_write($bin_disp)?>
<?S_response_write($unyang_disp)?>
<?S_response_write($yangin_disp)?>
<?S_response_write($gang_disp)?>
<?S_response_write($baekho_disp)?>
<?S_response_write($chenduk_disp)?>
<?S_response_write($wolduk_disp)?>
<?S_response_write($whang_disp)?>
<?S_response_write($chenju_disp)?>
<?S_response_write($gum_disp)?>
<?S_response_write($hakdang_disp)?>
<?S_response_write($cheneul_disp)?>