
<?
##############################################################################################12운성 산출
if (($my_day_h == '甲') && ($my_year_e == '亥')) {$star_year = '장생(長生)';}
if (($my_day_h == '甲') && ($my_year_e == '子')) {$star_year = '목욕(沐浴)';}
if (($my_day_h == '甲') && ($my_year_e == '丑')) {$star_year = '관대(冠帶)';}
if (($my_day_h == '甲') && ($my_year_e == '寅')) {$star_year = '건록(建祿)';}
if (($my_day_h == '甲') && ($my_year_e == '卯')) {$star_year = '제왕(帝旺)';}
if (($my_day_h == '甲') && ($my_year_e == '辰')) {$star_year = '쇄(衰)';}
if (($my_day_h == '甲') && ($my_year_e == '巳')) {$star_year = '병(病)';}
if (($my_day_h == '甲') && ($my_year_e == '午')) {$star_year = '사(死)';}
if (($my_day_h == '甲') && ($my_year_e == '未')) {$star_year = '묘(墓)';}
if (($my_day_h == '甲') && ($my_year_e == '申')) {$star_year = '절(絶)';}
if (($my_day_h == '甲') && ($my_year_e == '酉')) {$star_year = '태(胎)';}
if (($my_day_h == '甲') && ($my_year_e == '戌')) {$star_year = '양(養)';}

if (($my_day_h == '甲') && ($my_month_e == '亥')) {$star_month = '장생(長生)';}
if (($my_day_h == '甲') && ($my_month_e == '子')) {$star_month = '목욕(沐浴)';}
if (($my_day_h == '甲') && ($my_month_e == '丑')) {$star_month = '관대(冠帶)';}
if (($my_day_h == '甲') && ($my_month_e == '寅')) {$star_month = '건록(建祿)';}
if (($my_day_h == '甲') && ($my_month_e == '卯')) {$star_month = '제왕(帝旺)';}
if (($my_day_h == '甲') && ($my_month_e == '辰')) {$star_month = '쇄(衰)';}
if (($my_day_h == '甲') && ($my_month_e == '巳')) {$star_month = '병(病)';}
if (($my_day_h == '甲') && ($my_month_e == '午')) {$star_month = '사(死)';}
if (($my_day_h == '甲') && ($my_month_e == '未')) {$star_month = '묘(墓)';}
if (($my_day_h == '甲') && ($my_month_e == '申')) {$star_month = '절(絶)';}
if (($my_day_h == '甲') && ($my_month_e == '酉')) {$star_month = '태(胎)';}
if (($my_day_h == '甲') && ($my_month_e == '戌')) {$star_month = '양(養)';}

if (($my_day_h == '甲') && ($my_day_e == '亥')) {$star_day = '장생(長生)';}
if (($my_day_h == '甲') && ($my_day_e == '子')) {$star_day = '목욕(沐浴)';}
if (($my_day_h == '甲') && ($my_day_e == '丑')) {$star_day = '관대(冠帶)';}
if (($my_day_h == '甲') && ($my_day_e == '寅')) {$star_day = '건록(建祿)';}
if (($my_day_h == '甲') && ($my_day_e == '卯')) {$star_day = '제왕(帝旺)';}
if (($my_day_h == '甲') && ($my_day_e == '辰')) {$star_day = '쇄(衰)';}
if (($my_day_h == '甲') && ($my_day_e == '巳')) {$star_day = '병(病)';}
if (($my_day_h == '甲') && ($my_day_e == '午')) {$star_day = '사(死)';}
if (($my_day_h == '甲') && ($my_day_e == '未')) {$star_day = '묘(墓)';}
if (($my_day_h == '甲') && ($my_day_e == '申')) {$star_day = '절(絶)';}
if (($my_day_h == '甲') && ($my_day_e == '酉')) {$star_day = '태(胎)';}
if (($my_day_h == '甲') && ($my_day_e == '戌')) {$star_day = '양(養)';}

if (($my_day_h == '甲') && ($my_hour_e == '亥')) {$star_hour = '장생(長生)';}
if (($my_day_h == '甲') && ($my_hour_e == '子')) {$star_hour = '목욕(沐浴)';}
if (($my_day_h == '甲') && ($my_hour_e == '丑')) {$star_hour = '관대(冠帶)';}
if (($my_day_h == '甲') && ($my_hour_e == '寅')) {$star_hour = '건록(建祿)';}
if (($my_day_h == '甲') && ($my_hour_e == '卯')) {$star_hour = '제왕(帝旺)';}
if (($my_day_h == '甲') && ($my_hour_e == '辰')) {$star_hour = '쇄(衰)';}
if (($my_day_h == '甲') && ($my_hour_e == '巳')) {$star_hour = '병(病)';}
if (($my_day_h == '甲') && ($my_hour_e == '午')) {$star_hour = '사(死)';}
if (($my_day_h == '甲') && ($my_hour_e == '未')) {$star_hour = '묘(墓)';}
if (($my_day_h == '甲') && ($my_hour_e == '申')) {$star_hour = '절(絶)';}
if (($my_day_h == '甲') && ($my_hour_e == '酉')) {$star_hour = '태(胎)';}
if (($my_day_h == '甲') && ($my_hour_e == '戌')) {$star_hour = '양(養)';}
##################################################################
if (($my_day_h == '乙') && ($my_year_e == '午')) {$star_year = '장생(長生)';}
if (($my_day_h == '乙') && ($my_year_e == '巳')) {$star_year = '목욕(沐浴)';}
if (($my_day_h == '乙') && ($my_year_e == '辰')) {$star_year = '관대(冠帶)';}
if (($my_day_h == '乙') && ($my_year_e == '卯')) {$star_year = '건록(建祿)';}
if (($my_day_h == '乙') && ($my_year_e == '寅')) {$star_year = '제왕(帝旺)';}
if (($my_day_h == '乙') && ($my_year_e == '丑')) {$star_year = '쇄(衰)';}
if (($my_day_h == '乙') && ($my_year_e == '子')) {$star_year = '병(病)';}
if (($my_day_h == '乙') && ($my_year_e == '亥')) {$star_year = '사(死)';}
if (($my_day_h == '乙') && ($my_year_e == '戌')) {$star_year = '묘(墓)';}
if (($my_day_h == '乙') && ($my_year_e == '酉')) {$star_year = '절(絶)';}
if (($my_day_h == '乙') && ($my_year_e == '申')) {$star_year = '태(胎)';}
if (($my_day_h == '乙') && ($my_year_e == '未')) {$star_year = '양(養)';}

if (($my_day_h == '乙') && ($my_month_e == '午')) {$star_month = '장생(長生)';}
if (($my_day_h == '乙') && ($my_month_e == '巳')) {$star_month = '목욕(沐浴)';}
if (($my_day_h == '乙') && ($my_month_e == '辰')) {$star_month = '관대(冠帶)';}
if (($my_day_h == '乙') && ($my_month_e == '卯')) {$star_month = '건록(建祿)';}
if (($my_day_h == '乙') && ($my_month_e == '寅')) {$star_month = '제왕(帝旺)';}
if (($my_day_h == '乙') && ($my_month_e == '丑')) {$star_month = '쇄(衰)';}
if (($my_day_h == '乙') && ($my_month_e == '子')) {$star_month = '병(病)';}
if (($my_day_h == '乙') && ($my_month_e == '亥')) {$star_month = '사(死)';}
if (($my_day_h == '乙') && ($my_month_e == '戌')) {$star_month = '묘(墓)';}
if (($my_day_h == '乙') && ($my_month_e == '酉')) {$star_month = '절(絶)';}
if (($my_day_h == '乙') && ($my_month_e == '申')) {$star_month = '태(胎)';}
if (($my_day_h == '乙') && ($my_month_e == '未')) {$star_month = '양(養)';}

if (($my_day_h == '乙') && ($my_day_e == '午')) {$star_day = '장생(長生)';}
if (($my_day_h == '乙') && ($my_day_e == '巳')) {$star_day = '목욕(沐浴)';}
if (($my_day_h == '乙') && ($my_day_e == '辰')) {$star_day = '관대(冠帶)';}
if (($my_day_h == '乙') && ($my_day_e == '卯')) {$star_day = '건록(建祿)';}
if (($my_day_h == '乙') && ($my_day_e == '寅')) {$star_day = '제왕(帝旺)';}
if (($my_day_h == '乙') && ($my_day_e == '丑')) {$star_day = '쇄(衰)';}
if (($my_day_h == '乙') && ($my_day_e == '子')) {$star_day = '병(病)';}
if (($my_day_h == '乙') && ($my_day_e == '亥')) {$star_day = '사(死)';}
if (($my_day_h == '乙') && ($my_day_e == '戌')) {$star_day = '묘(墓)';}
if (($my_day_h == '乙') && ($my_day_e == '酉')) {$star_day = '절(絶)';}
if (($my_day_h == '乙') && ($my_day_e == '申')) {$star_day = '태(胎)';}
if (($my_day_h == '乙') && ($my_day_e == '未')) {$star_day = '양(養)';}

if (($my_day_h == '乙') && ($my_hour_e == '午')) {$star_hour = '장생(長生)';}
if (($my_day_h == '乙') && ($my_hour_e == '巳')) {$star_hour = '목욕(沐浴)';}
if (($my_day_h == '乙') && ($my_hour_e == '辰')) {$star_hour = '관대(冠帶)';}
if (($my_day_h == '乙') && ($my_hour_e == '卯')) {$star_hour = '건록(建祿)';}
if (($my_day_h == '乙') && ($my_hour_e == '寅')) {$star_hour = '제왕(帝旺)';}
if (($my_day_h == '乙') && ($my_hour_e == '丑')) {$star_hour = '쇄(衰)';}
if (($my_day_h == '乙') && ($my_hour_e == '子')) {$star_hour = '병(病)';}
if (($my_day_h == '乙') && ($my_hour_e == '亥')) {$star_hour = '사(死)';}
if (($my_day_h == '乙') && ($my_hour_e == '戌')) {$star_hour = '묘(墓)';}
if (($my_day_h == '乙') && ($my_hour_e == '酉')) {$star_hour = '절(絶)';}
if (($my_day_h == '乙') && ($my_hour_e == '申')) {$star_hour = '태(胎)';}
if (($my_day_h == '乙') && ($my_hour_e == '未')) {$star_hour = '양(養)';}
#####################################################################
if (($my_day_h == '丙') && ($my_year_e == '寅')) {$star_year = '장생(長生)';}
if (($my_day_h == '丙') && ($my_year_e == '卯')) {$star_year = '목욕(沐浴)';}
if (($my_day_h == '丙') && ($my_year_e == '辰')) {$star_year = '관대(冠帶)';}
if (($my_day_h == '丙') && ($my_year_e == '巳')) {$star_year = '건록(建祿)';}
if (($my_day_h == '丙') && ($my_year_e == '午')) {$star_year = '제왕(帝旺)';}
if (($my_day_h == '丙') && ($my_year_e == '未')) {$star_year = '쇄(衰)';}
if (($my_day_h == '丙') && ($my_year_e == '申')) {$star_year = '병(病)';}
if (($my_day_h == '丙') && ($my_year_e == '酉')) {$star_year = '사(死)';}
if (($my_day_h == '丙') && ($my_year_e == '戌')) {$star_year = '묘(墓)';}
if (($my_day_h == '丙') && ($my_year_e == '亥')) {$star_year = '절(絶)';}
if (($my_day_h == '丙') && ($my_year_e == '子')) {$star_year = '태(胎)';}
if (($my_day_h == '丙') && ($my_year_e == '丑')) {$star_year = '양(養)';}

if (($my_day_h == '丙') && ($my_month_e == '寅')) {$star_month = '장생(長生)';}
if (($my_day_h == '丙') && ($my_month_e == '卯')) {$star_month = '목욕(沐浴)';}
if (($my_day_h == '丙') && ($my_month_e == '辰')) {$star_month = '관대(冠帶)';}
if (($my_day_h == '丙') && ($my_month_e == '巳')) {$star_month = '건록(建祿)';}
if (($my_day_h == '丙') && ($my_month_e == '午')) {$star_month = '제왕(帝旺)';}
if (($my_day_h == '丙') && ($my_month_e == '未')) {$star_month = '쇄(衰)';}
if (($my_day_h == '丙') && ($my_month_e == '申')) {$star_month = '병(病)';}
if (($my_day_h == '丙') && ($my_month_e == '酉')) {$star_month = '사(死)';}
if (($my_day_h == '丙') && ($my_month_e == '戌')) {$star_month = '묘(墓)';}
if (($my_day_h == '丙') && ($my_month_e == '亥')) {$star_month = '절(絶)';}
if (($my_day_h == '丙') && ($my_month_e == '子')) {$star_month = '태(胎)';}
if (($my_day_h == '丙') && ($my_month_e == '丑')) {$star_month = '양(養)';}

if (($my_day_h == '丙') && ($my_day_e == '寅')) {$star_day = '장생(長生)';}
if (($my_day_h == '丙') && ($my_day_e == '卯')) {$star_day = '목욕(沐浴)';}
if (($my_day_h == '丙') && ($my_day_e == '辰')) {$star_day = '관대(冠帶)';}
if (($my_day_h == '丙') && ($my_day_e == '巳')) {$star_day = '건록(建祿)';}
if (($my_day_h == '丙') && ($my_day_e == '午')) {$star_day = '제왕(帝旺)';}
if (($my_day_h == '丙') && ($my_day_e == '未')) {$star_day = '쇄(衰)';}
if (($my_day_h == '丙') && ($my_day_e == '申')) {$star_day = '병(病)';}
if (($my_day_h == '丙') && ($my_day_e == '酉')) {$star_day = '사(死)';}
if (($my_day_h == '丙') && ($my_day_e == '戌')) {$star_day = '묘(墓)';}
if (($my_day_h == '丙') && ($my_day_e == '亥')) {$star_day = '절(絶)';}
if (($my_day_h == '丙') && ($my_day_e == '子')) {$star_day = '태(胎)';}
if (($my_day_h == '丙') && ($my_day_e == '丑')) {$star_day = '양(養)';}

if (($my_day_h == '丙') && ($my_hour_e == '寅')) {$star_hour = '장생(長生)';}
if (($my_day_h == '丙') && ($my_hour_e == '卯')) {$star_hour = '목욕(沐浴)';}
if (($my_day_h == '丙') && ($my_hour_e == '辰')) {$star_hour = '관대(冠帶)';}
if (($my_day_h == '丙') && ($my_hour_e == '巳')) {$star_hour = '건록(建祿)';}
if (($my_day_h == '丙') && ($my_hour_e == '午')) {$star_hour = '제왕(帝旺)';}
if (($my_day_h == '丙') && ($my_hour_e == '未')) {$star_hour = '쇄(衰)';}
if (($my_day_h == '丙') && ($my_hour_e == '申')) {$star_hour = '병(病)';}
if (($my_day_h == '丙') && ($my_hour_e == '酉')) {$star_hour = '사(死)';}
if (($my_day_h == '丙') && ($my_hour_e == '戌')) {$star_hour = '묘(墓)';}
if (($my_day_h == '丙') && ($my_hour_e == '亥')) {$star_hour = '절(絶)';}
if (($my_day_h == '丙') && ($my_hour_e == '子')) {$star_hour = '태(胎)';}
if (($my_day_h == '丙') && ($my_hour_e == '丑')) {$star_hour = '양(養)';}
######################################################################
if (($my_day_h == '丁') && ($my_year_e == '酉')) {$star_year = '장생(長生)';}
if (($my_day_h == '丁') && ($my_year_e == '申')) {$star_year = '목욕(沐浴)';}
if (($my_day_h == '丁') && ($my_year_e == '未')) {$star_year = '관대(冠帶)';}
if (($my_day_h == '丁') && ($my_year_e == '午')) {$star_year = '건록(建祿)';}
if (($my_day_h == '丁') && ($my_year_e == '巳')) {$star_year = '제왕(帝旺)';}
if (($my_day_h == '丁') && ($my_year_e == '辰')) {$star_year = '쇄(衰)';}
if (($my_day_h == '丁') && ($my_year_e == '卯')) {$star_year = '병(病)';}
if (($my_day_h == '丁') && ($my_year_e == '寅')) {$star_year = '사(死)';}
if (($my_day_h == '丁') && ($my_year_e == '丑')) {$star_year = '묘(墓)';}
if (($my_day_h == '丁') && ($my_year_e == '子')) {$star_year = '절(絶)';}
if (($my_day_h == '丁') && ($my_year_e == '亥')) {$star_year = '태(胎)';}
if (($my_day_h == '丁') && ($my_year_e == '戌')) {$star_year = '양(養)';}

if (($my_day_h == '丁') && ($my_month_e == '酉')) {$star_month = '장생(長生)';}
if (($my_day_h == '丁') && ($my_month_e == '申')) {$star_month = '목욕(沐浴)';}
if (($my_day_h == '丁') && ($my_month_e == '未')) {$star_month = '관대(冠帶)';}
if (($my_day_h == '丁') && ($my_month_e == '午')) {$star_month = '건록(建祿)';}
if (($my_day_h == '丁') && ($my_month_e == '巳')) {$star_month = '제왕(帝旺)';}
if (($my_day_h == '丁') && ($my_month_e == '辰')) {$star_month = '쇄(衰)';}
if (($my_day_h == '丁') && ($my_month_e == '卯')) {$star_month = '병(病)';}
if (($my_day_h == '丁') && ($my_month_e == '寅')) {$star_month = '사(死)';}
if (($my_day_h == '丁') && ($my_month_e == '丑')) {$star_month = '묘(墓)';}
if (($my_day_h == '丁') && ($my_month_e == '子')) {$star_month = '절(絶)';}
if (($my_day_h == '丁') && ($my_month_e == '亥')) {$star_month = '태(胎)';}
if (($my_day_h == '丁') && ($my_month_e == '戌')) {$star_month = '양(養)';}

if (($my_day_h == '丁') && ($my_day_e == '酉')) {$star_day = '장생(長生)';}
if (($my_day_h == '丁') && ($my_day_e == '申')) {$star_day = '목욕(沐浴)';}
if (($my_day_h == '丁') && ($my_day_e == '未')) {$star_day = '관대(冠帶)';}
if (($my_day_h == '丁') && ($my_day_e == '午')) {$star_day = '건록(建祿)';}
if (($my_day_h == '丁') && ($my_day_e == '巳')) {$star_day = '제왕(帝旺)';}
if (($my_day_h == '丁') && ($my_day_e == '辰')) {$star_day = '쇄(衰)';}
if (($my_day_h == '丁') && ($my_day_e == '卯')) {$star_day = '병(病)';}
if (($my_day_h == '丁') && ($my_day_e == '寅')) {$star_day = '사(死)';}
if (($my_day_h == '丁') && ($my_day_e == '丑')) {$star_day = '묘(墓)';}
if (($my_day_h == '丁') && ($my_day_e == '子')) {$star_day = '절(絶)';}
if (($my_day_h == '丁') && ($my_day_e == '亥')) {$star_day = '태(胎)';}
if (($my_day_h == '丁') && ($my_day_e == '戌')) {$star_day = '양(養)';}

if (($my_day_h == '丁') && ($my_hour_e == '酉')) {$star_hour = '장생(長生)';}
if (($my_day_h == '丁') && ($my_hour_e == '申')) {$star_hour = '목욕(沐浴)';}
if (($my_day_h == '丁') && ($my_hour_e == '未')) {$star_hour = '관대(冠帶)';}
if (($my_day_h == '丁') && ($my_hour_e == '午')) {$star_hour = '건록(建祿)';}
if (($my_day_h == '丁') && ($my_hour_e == '巳')) {$star_hour = '제왕(帝旺)';}
if (($my_day_h == '丁') && ($my_hour_e == '辰')) {$star_hour = '쇄(衰)';}
if (($my_day_h == '丁') && ($my_hour_e == '卯')) {$star_hour = '병(病)';}
if (($my_day_h == '丁') && ($my_hour_e == '寅')) {$star_hour = '사(死)';}
if (($my_day_h == '丁') && ($my_hour_e == '丑')) {$star_hour = '묘(墓)';}
if (($my_day_h == '丁') && ($my_hour_e == '子')) {$star_hour = '절(絶)';}
if (($my_day_h == '丁') && ($my_hour_e == '亥')) {$star_hour = '태(胎)';}
if (($my_day_h == '丁') && ($my_hour_e == '戌')) {$star_hour = '양(養)';}
###########################################################################
if (($my_day_h == '戊') && ($my_year_e == '寅')) {$star_year = '장생(長生)';}
if (($my_day_h == '戊') && ($my_year_e == '卯')) {$star_year = '목욕(沐浴)';}
if (($my_day_h == '戊') && ($my_year_e == '辰')) {$star_year = '관대(冠帶)';}
if (($my_day_h == '戊') && ($my_year_e == '巳')) {$star_year = '건록(建祿)';}
if (($my_day_h == '戊') && ($my_year_e == '午')) {$star_year = '제왕(帝旺)';}
if (($my_day_h == '戊') && ($my_year_e == '未')) {$star_year = '쇄(衰)';}
if (($my_day_h == '戊') && ($my_year_e == '申')) {$star_year = '병(病)';}
if (($my_day_h == '戊') && ($my_year_e == '酉')) {$star_year = '사(死)';}
if (($my_day_h == '戊') && ($my_year_e == '戌')) {$star_year = '묘(墓)';}
if (($my_day_h == '戊') && ($my_year_e == '亥')) {$star_year = '절(絶)';}
if (($my_day_h == '戊') && ($my_year_e == '子')) {$star_year = '태(胎)';}
if (($my_day_h == '戊') && ($my_year_e == '丑')) {$star_year = '양(養)';}

if (($my_day_h == '戊') && ($my_month_e == '寅')) {$star_month = '장생(長生)';}
if (($my_day_h == '戊') && ($my_month_e == '卯')) {$star_month = '목욕(沐浴)';}
if (($my_day_h == '戊') && ($my_month_e == '辰')) {$star_month = '관대(冠帶)';}
if (($my_day_h == '戊') && ($my_month_e == '巳')) {$star_month = '건록(建祿)';}
if (($my_day_h == '戊') && ($my_month_e == '午')) {$star_month = '제왕(帝旺)';}
if (($my_day_h == '戊') && ($my_month_e == '未')) {$star_month = '쇄(衰)';}
if (($my_day_h == '戊') && ($my_month_e == '申')) {$star_month = '병(病)';}
if (($my_day_h == '戊') && ($my_month_e == '酉')) {$star_month = '사(死)';}
if (($my_day_h == '戊') && ($my_month_e == '戌')) {$star_month = '묘(墓)';}
if (($my_day_h == '戊') && ($my_month_e == '亥')) {$star_month = '절(絶)';}
if (($my_day_h == '戊') && ($my_month_e == '子')) {$star_month = '태(胎)';}
if (($my_day_h == '戊') && ($my_month_e == '丑')) {$star_month = '양(養)';}

if (($my_day_h == '戊') && ($my_day_e == '寅')) {$star_day = '장생(長生)';}
if (($my_day_h == '戊') && ($my_day_e == '卯')) {$star_day = '목욕(沐浴)';}
if (($my_day_h == '戊') && ($my_day_e == '辰')) {$star_day = '관대(冠帶)';}
if (($my_day_h == '戊') && ($my_day_e == '巳')) {$star_day = '건록(建祿)';}
if (($my_day_h == '戊') && ($my_day_e == '午')) {$star_day = '제왕(帝旺)';}
if (($my_day_h == '戊') && ($my_day_e == '未')) {$star_day = '쇄(衰)';}
if (($my_day_h == '戊') && ($my_day_e == '申')) {$star_day = '병(病)';}
if (($my_day_h == '戊') && ($my_day_e == '酉')) {$star_day = '사(死)';}
if (($my_day_h == '戊') && ($my_day_e == '戌')) {$star_day = '묘(墓)';}
if (($my_day_h == '戊') && ($my_day_e == '亥')) {$star_day = '절(絶)';}
if (($my_day_h == '戊') && ($my_day_e == '子')) {$star_day = '태(胎)';}
if (($my_day_h == '戊') && ($my_day_e == '丑')) {$star_day = '양(養)';}

if (($my_day_h == '戊') && ($my_hour_e == '寅')) {$star_hour = '장생(長生)';}
if (($my_day_h == '戊') && ($my_hour_e == '卯')) {$star_hour = '목욕(沐浴)';}
if (($my_day_h == '戊') && ($my_hour_e == '辰')) {$star_hour = '관대(冠帶)';}
if (($my_day_h == '戊') && ($my_hour_e == '巳')) {$star_hour = '건록(建祿)';}
if (($my_day_h == '戊') && ($my_hour_e == '午')) {$star_hour = '제왕(帝旺)';}
if (($my_day_h == '戊') && ($my_hour_e == '未')) {$star_hour = '쇄(衰)';}
if (($my_day_h == '戊') && ($my_hour_e == '申')) {$star_hour = '병(病)';}
if (($my_day_h == '戊') && ($my_hour_e == '酉')) {$star_hour = '사(死)';}
if (($my_day_h == '戊') && ($my_hour_e == '戌')) {$star_hour = '묘(墓)';}
if (($my_day_h == '戊') && ($my_hour_e == '亥')) {$star_hour = '절(絶)';}
if (($my_day_h == '戊') && ($my_hour_e == '子')) {$star_hour = '태(胎)';}
if (($my_day_h == '戊') && ($my_hour_e == '丑')) {$star_hour = '양(養)';}
########################################################################
if (($my_day_h == '己') && ($my_year_e == '酉')) {$star_year = '장생(長生)';}
if (($my_day_h == '己') && ($my_year_e == '申')) {$star_year = '목욕(沐浴)';}
if (($my_day_h == '己') && ($my_year_e == '未')) {$star_year = '관대(冠帶)';}
if (($my_day_h == '己') && ($my_year_e == '午')) {$star_year = '건록(建祿)';}
if (($my_day_h == '己') && ($my_year_e == '巳')) {$star_year = '제왕(帝旺)';}
if (($my_day_h == '己') && ($my_year_e == '辰')) {$star_year = '쇄(衰)';}
if (($my_day_h == '己') && ($my_year_e == '卯')) {$star_year = '병(病)';}
if (($my_day_h == '己') && ($my_year_e == '寅')) {$star_year = '사(死)';}
if (($my_day_h == '己') && ($my_year_e == '丑')) {$star_year = '묘(墓)';}
if (($my_day_h == '己') && ($my_year_e == '子')) {$star_year = '절(絶)';}
if (($my_day_h == '己') && ($my_year_e == '亥')) {$star_year = '태(胎)';}
if (($my_day_h == '己') && ($my_year_e == '戌')) {$star_year = '양(養)';}

if (($my_day_h == '己') && ($my_month_e == '酉')) {$star_month = '장생(長生)';}
if (($my_day_h == '己') && ($my_month_e == '申')) {$star_month = '목욕(沐浴)';}
if (($my_day_h == '己') && ($my_month_e == '未')) {$star_month = '관대(冠帶)';}
if (($my_day_h == '己') && ($my_month_e == '午')) {$star_month = '건록(建祿)';}
if (($my_day_h == '己') && ($my_month_e == '巳')) {$star_month = '제왕(帝旺)';}
if (($my_day_h == '己') && ($my_month_e == '辰')) {$star_month = '쇄(衰)';}
if (($my_day_h == '己') && ($my_month_e == '卯')) {$star_month = '병(病)';}
if (($my_day_h == '己') && ($my_month_e == '寅')) {$star_month = '사(死)';}
if (($my_day_h == '己') && ($my_month_e == '丑')) {$star_month = '묘(墓)';}
if (($my_day_h == '己') && ($my_month_e == '子')) {$star_month = '절(絶)';}
if (($my_day_h == '己') && ($my_month_e == '亥')) {$star_month = '태(胎)';}
if (($my_day_h == '己') && ($my_month_e == '戌')) {$star_month = '양(養)';}

if (($my_day_h == '己') && ($my_day_e == '酉')) {$star_day = '장생(長生)';}
if (($my_day_h == '己') && ($my_day_e == '申')) {$star_day = '목욕(沐浴)';}
if (($my_day_h == '己') && ($my_day_e == '未')) {$star_day = '관대(冠帶)';}
if (($my_day_h == '己') && ($my_day_e == '午')) {$star_day = '건록(建祿)';}
if (($my_day_h == '己') && ($my_day_e == '巳')) {$star_day = '제왕(帝旺)';}
if (($my_day_h == '己') && ($my_day_e == '辰')) {$star_day = '쇄(衰)';}
if (($my_day_h == '己') && ($my_day_e == '卯')) {$star_day = '병(病)';}
if (($my_day_h == '己') && ($my_day_e == '寅')) {$star_day = '사(死)';}
if (($my_day_h == '己') && ($my_day_e == '丑')) {$star_day = '묘(墓)';}
if (($my_day_h == '己') && ($my_day_e == '子')) {$star_day = '절(絶)';}
if (($my_day_h == '己') && ($my_day_e == '亥')) {$star_day = '태(胎)';}
if (($my_day_h == '己') && ($my_day_e == '戌')) {$star_day = '양(養)';}

if (($my_day_h == '己') && ($my_hour_e == '酉')) {$star_hour = '장생(長生)';}
if (($my_day_h == '己') && ($my_hour_e == '申')) {$star_hour = '목욕(沐浴)';}
if (($my_day_h == '己') && ($my_hour_e == '未')) {$star_hour = '관대(冠帶)';}
if (($my_day_h == '己') && ($my_hour_e == '午')) {$star_hour = '건록(建祿)';}
if (($my_day_h == '己') && ($my_hour_e == '巳')) {$star_hour = '제왕(帝旺)';}
if (($my_day_h == '己') && ($my_hour_e == '辰')) {$star_hour = '쇄(衰)';}
if (($my_day_h == '己') && ($my_hour_e == '卯')) {$star_hour = '병(病)';}
if (($my_day_h == '己') && ($my_hour_e == '寅')) {$star_hour = '사(死)';}
if (($my_day_h == '己') && ($my_hour_e == '丑')) {$star_hour = '묘(墓)';}
if (($my_day_h == '己') && ($my_hour_e == '子')) {$star_hour = '절(絶)';}
if (($my_day_h == '己') && ($my_hour_e == '亥')) {$star_hour = '태(胎)';}
if (($my_day_h == '己') && ($my_hour_e == '戌')) {$star_hour = '양(養)';}
########################################################################
if (($my_day_h == '庚') && ($my_year_e == '巳')) {$star_year = '장생(長生)';}
if (($my_day_h == '庚') && ($my_year_e == '午')) {$star_year = '목욕(沐浴)';}
if (($my_day_h == '庚') && ($my_year_e == '未')) {$star_year = '관대(冠帶)';}
if (($my_day_h == '庚') && ($my_year_e == '申')) {$star_year = '건록(建祿)';}
if (($my_day_h == '庚') && ($my_year_e == '酉')) {$star_year = '제왕(帝旺)';}
if (($my_day_h == '庚') && ($my_year_e == '戌')) {$star_year = '쇄(衰)';}
if (($my_day_h == '庚') && ($my_year_e == '亥')) {$star_year = '병(病)';}
if (($my_day_h == '庚') && ($my_year_e == '子')) {$star_year = '사(死)';}
if (($my_day_h == '庚') && ($my_year_e == '丑')) {$star_year = '묘(墓)';}
if (($my_day_h == '庚') && ($my_year_e == '寅')) {$star_year = '절(絶)';}
if (($my_day_h == '庚') && ($my_year_e == '卯')) {$star_year = '태(胎)';}
if (($my_day_h == '庚') && ($my_year_e == '辰')) {$star_year = '양(養)';}

if (($my_day_h == '庚') && ($my_month_e == '巳')) {$star_month = '장생(長生)';}
if (($my_day_h == '庚') && ($my_month_e == '午')) {$star_month = '목욕(沐浴)';}
if (($my_day_h == '庚') && ($my_month_e == '未')) {$star_month = '관대(冠帶)';}
if (($my_day_h == '庚') && ($my_month_e == '申')) {$star_month = '건록(建祿)';}
if (($my_day_h == '庚') && ($my_month_e == '酉')) {$star_month = '제왕(帝旺)';}
if (($my_day_h == '庚') && ($my_month_e == '戌')) {$star_month = '쇄(衰)';}
if (($my_day_h == '庚') && ($my_month_e == '亥')) {$star_month = '병(病)';}
if (($my_day_h == '庚') && ($my_month_e == '子')) {$star_month = '사(死)';}
if (($my_day_h == '庚') && ($my_month_e == '丑')) {$star_month = '묘(墓)';}
if (($my_day_h == '庚') && ($my_month_e == '寅')) {$star_month = '절(絶)';}
if (($my_day_h == '庚') && ($my_month_e == '卯')) {$star_month = '태(胎)';}
if (($my_day_h == '庚') && ($my_month_e == '辰')) {$star_month = '양(養)';}

if (($my_day_h == '庚') && ($my_day_e == '巳')) {$star_day = '장생(長生)';}
if (($my_day_h == '庚') && ($my_day_e == '午')) {$star_day = '목욕(沐浴)';}
if (($my_day_h == '庚') && ($my_day_e == '未')) {$star_day = '관대(冠帶)';}
if (($my_day_h == '庚') && ($my_day_e == '申')) {$star_day = '건록(建祿)';}
if (($my_day_h == '庚') && ($my_day_e == '酉')) {$star_day = '제왕(帝旺)';}
if (($my_day_h == '庚') && ($my_day_e == '戌')) {$star_day = '쇄(衰)';}
if (($my_day_h == '庚') && ($my_day_e == '亥')) {$star_day = '병(病)';}
if (($my_day_h == '庚') && ($my_day_e == '子')) {$star_day = '사(死)';}
if (($my_day_h == '庚') && ($my_day_e == '丑')) {$star_day = '묘(墓)';}
if (($my_day_h == '庚') && ($my_day_e == '寅')) {$star_day = '절(絶)';}
if (($my_day_h == '庚') && ($my_day_e == '卯')) {$star_day = '태(胎)';}
if (($my_day_h == '庚') && ($my_day_e == '辰')) {$star_day = '양(養)';}

if (($my_day_h == '庚') && ($my_hour_e == '巳')) {$star_hour = '장생(長生)';}
if (($my_day_h == '庚') && ($my_hour_e == '午')) {$star_hour = '목욕(沐浴)';}
if (($my_day_h == '庚') && ($my_hour_e == '未')) {$star_hour = '관대(冠帶)';}
if (($my_day_h == '庚') && ($my_hour_e == '申')) {$star_hour = '건록(建祿)';}
if (($my_day_h == '庚') && ($my_hour_e == '酉')) {$star_hour = '제왕(帝旺)';}
if (($my_day_h == '庚') && ($my_hour_e == '戌')) {$star_hour = '쇄(衰)';}
if (($my_day_h == '庚') && ($my_hour_e == '亥')) {$star_hour = '병(病)';}
if (($my_day_h == '庚') && ($my_hour_e == '子')) {$star_hour = '사(死)';}
if (($my_day_h == '庚') && ($my_hour_e == '丑')) {$star_hour = '묘(墓)';}
if (($my_day_h == '庚') && ($my_hour_e == '寅')) {$star_hour = '절(絶)';}
if (($my_day_h == '庚') && ($my_hour_e == '卯')) {$star_hour = '태(胎)';}
if (($my_day_h == '庚') && ($my_hour_e == '辰')) {$star_hour = '양(養)';}
########################################################################
if (($my_day_h == '辛') && ($my_year_e == '子')) {$star_year = '장생(長生)';}
if (($my_day_h == '辛') && ($my_year_e == '亥')) {$star_year = '목욕(沐浴)';}
if (($my_day_h == '辛') && ($my_year_e == '戌')) {$star_year = '관대(冠帶)';}
if (($my_day_h == '辛') && ($my_year_e == '酉')) {$star_year = '건록(建祿)';}
if (($my_day_h == '辛') && ($my_year_e == '申')) {$star_year = '제왕(帝旺)';}
if (($my_day_h == '辛') && ($my_year_e == '未')) {$star_year = '쇄(衰)';}
if (($my_day_h == '辛') && ($my_year_e == '午')) {$star_year = '병(病)';}
if (($my_day_h == '辛') && ($my_year_e == '巳')) {$star_year = '사(死)';}
if (($my_day_h == '辛') && ($my_year_e == '辰')) {$star_year = '묘(墓)';}
if (($my_day_h == '辛') && ($my_year_e == '卯')) {$star_year = '절(絶)';}
if (($my_day_h == '辛') && ($my_year_e == '寅')) {$star_year = '태(胎)';}
if (($my_day_h == '辛') && ($my_year_e == '丑')) {$star_year = '양(養)';}

if (($my_day_h == '辛') && ($my_month_e == '子')) {$star_month = '장생(長生)';}
if (($my_day_h == '辛') && ($my_month_e == '亥')) {$star_month = '목욕(沐浴)';}
if (($my_day_h == '辛') && ($my_month_e == '戌')) {$star_month = '관대(冠帶)';}
if (($my_day_h == '辛') && ($my_month_e == '酉')) {$star_month = '건록(建祿)';}
if (($my_day_h == '辛') && ($my_month_e == '申')) {$star_month = '제왕(帝旺)';}
if (($my_day_h == '辛') && ($my_month_e == '未')) {$star_month = '쇄(衰)';}
if (($my_day_h == '辛') && ($my_month_e == '午')) {$star_month = '병(病)';}
if (($my_day_h == '辛') && ($my_month_e == '巳')) {$star_month = '사(死)';}
if (($my_day_h == '辛') && ($my_month_e == '辰')) {$star_month = '묘(墓)';}
if (($my_day_h == '辛') && ($my_month_e == '卯')) {$star_month = '절(絶)';}
if (($my_day_h == '辛') && ($my_month_e == '寅')) {$star_month = '태(胎)';}
if (($my_day_h == '辛') && ($my_month_e == '丑')) {$star_month = '양(養)';}

if (($my_day_h == '辛') && ($my_day_e == '子')) {$star_day = '장생(長生)';}
if (($my_day_h == '辛') && ($my_day_e == '亥')) {$star_day = '목욕(沐浴)';}
if (($my_day_h == '辛') && ($my_day_e == '戌')) {$star_day = '관대(冠帶)';}
if (($my_day_h == '辛') && ($my_day_e == '酉')) {$star_day = '건록(建祿)';}
if (($my_day_h == '辛') && ($my_day_e == '申')) {$star_day = '제왕(帝旺)';}
if (($my_day_h == '辛') && ($my_day_e == '未')) {$star_day = '쇄(衰)';}
if (($my_day_h == '辛') && ($my_day_e == '午')) {$star_day = '병(病)';}
if (($my_day_h == '辛') && ($my_day_e == '巳')) {$star_day = '사(死)';}
if (($my_day_h == '辛') && ($my_day_e == '辰')) {$star_day = '묘(墓)';}
if (($my_day_h == '辛') && ($my_day_e == '卯')) {$star_day = '절(絶)';}
if (($my_day_h == '辛') && ($my_day_e == '寅')) {$star_day = '태(胎)';}
if (($my_day_h == '辛') && ($my_day_e == '丑')) {$star_day = '양(養)';}

if (($my_day_h == '辛') && ($my_hour_e == '子')) {$star_hour = '장생(長生)';}
if (($my_day_h == '辛') && ($my_hour_e == '亥')) {$star_hour = '목욕(沐浴)';}
if (($my_day_h == '辛') && ($my_hour_e == '戌')) {$star_hour = '관대(冠帶)';}
if (($my_day_h == '辛') && ($my_hour_e == '酉')) {$star_hour = '건록(建祿)';}
if (($my_day_h == '辛') && ($my_hour_e == '申')) {$star_hour = '제왕(帝旺)';}
if (($my_day_h == '辛') && ($my_hour_e == '未')) {$star_hour = '쇄(衰)';}
if (($my_day_h == '辛') && ($my_hour_e == '午')) {$star_hour = '병(病)';}
if (($my_day_h == '辛') && ($my_hour_e == '巳')) {$star_hour = '사(死)';}
if (($my_day_h == '辛') && ($my_hour_e == '辰')) {$star_hour = '묘(墓)';}
if (($my_day_h == '辛') && ($my_hour_e == '卯')) {$star_hour = '절(絶)';}
if (($my_day_h == '辛') && ($my_hour_e == '寅')) {$star_hour = '태(胎)';}
if (($my_day_h == '辛') && ($my_hour_e == '丑')) {$star_hour = '양(養)';}
#######################################################################
if (($my_day_h == '壬') && ($my_year_e == '申')) {$star_year = '장생(長生)';}
if (($my_day_h == '壬') && ($my_year_e == '酉')) {$star_year = '목욕(沐浴)';}
if (($my_day_h == '壬') && ($my_year_e == '戌')) {$star_year = '관대(冠帶)';}
if (($my_day_h == '壬') && ($my_year_e == '亥')) {$star_year = '건록(建祿)';}
if (($my_day_h == '壬') && ($my_year_e == '子')) {$star_year = '제왕(帝旺)';}
if (($my_day_h == '壬') && ($my_year_e == '丑')) {$star_year = '쇄(衰)';}
if (($my_day_h == '壬') && ($my_year_e == '寅')) {$star_year = '병(病)';}
if (($my_day_h == '壬') && ($my_year_e == '卯')) {$star_year = '사(死)';}
if (($my_day_h == '壬') && ($my_year_e == '辰')) {$star_year = '묘(墓)';}
if (($my_day_h == '壬') && ($my_year_e == '巳')) {$star_year = '절(絶)';}
if (($my_day_h == '壬') && ($my_year_e == '午')) {$star_year = '태(胎)';}
if (($my_day_h == '壬') && ($my_year_e == '未')) {$star_year = '양(養)';}

if (($my_day_h == '壬') && ($my_month_e == '申')) {$star_month = '장생(長生)';}
if (($my_day_h == '壬') && ($my_month_e == '酉')) {$star_month = '목욕(沐浴)';}
if (($my_day_h == '壬') && ($my_month_e == '戌')) {$star_month = '관대(冠帶)';}
if (($my_day_h == '壬') && ($my_month_e == '亥')) {$star_month = '건록(建祿)';}
if (($my_day_h == '壬') && ($my_month_e == '子')) {$star_month = '제왕(帝旺)';}
if (($my_day_h == '壬') && ($my_month_e == '丑')) {$star_month = '쇄(衰)';}
if (($my_day_h == '壬') && ($my_month_e == '寅')) {$star_month = '병(病)';}
if (($my_day_h == '壬') && ($my_month_e == '卯')) {$star_month = '사(死)';}
if (($my_day_h == '壬') && ($my_month_e == '辰')) {$star_month = '묘(墓)';}
if (($my_day_h == '壬') && ($my_month_e == '巳')) {$star_month = '절(絶)';}
if (($my_day_h == '壬') && ($my_month_e == '午')) {$star_month = '태(胎)';}
if (($my_day_h == '壬') && ($my_month_e == '未')) {$star_month = '양(養)';}

if (($my_day_h == '壬') && ($my_day_e == '申')) {$star_day = '장생(長生)';}
if (($my_day_h == '壬') && ($my_day_e == '酉')) {$star_day = '목욕(沐浴)';}
if (($my_day_h == '壬') && ($my_day_e == '戌')) {$star_day = '관대(冠帶)';}
if (($my_day_h == '壬') && ($my_day_e == '亥')) {$star_day = '건록(建祿)';}
if (($my_day_h == '壬') && ($my_day_e == '子')) {$star_day = '제왕(帝旺)';}
if (($my_day_h == '壬') && ($my_day_e == '丑')) {$star_day = '쇄(衰)';}
if (($my_day_h == '壬') && ($my_day_e == '寅')) {$star_day = '병(病)';}
if (($my_day_h == '壬') && ($my_day_e == '卯')) {$star_day = '사(死)';}
if (($my_day_h == '壬') && ($my_day_e == '辰')) {$star_day = '묘(墓)';}
if (($my_day_h == '壬') && ($my_day_e == '巳')) {$star_day = '절(絶)';}
if (($my_day_h == '壬') && ($my_day_e == '午')) {$star_day = '태(胎)';}
if (($my_day_h == '壬') && ($my_day_e == '未')) {$star_day = '양(養)';}

if (($my_day_h == '壬') && ($my_hour_e == '申')) {$star_hour = '장생(長生)';}
if (($my_day_h == '壬') && ($my_hour_e == '酉')) {$star_hour = '목욕(沐浴)';}
if (($my_day_h == '壬') && ($my_hour_e == '戌')) {$star_hour = '관대(冠帶)';}
if (($my_day_h == '壬') && ($my_hour_e == '亥')) {$star_hour = '건록(建祿)';}
if (($my_day_h == '壬') && ($my_hour_e == '子')) {$star_hour = '제왕(帝旺)';}
if (($my_day_h == '壬') && ($my_hour_e == '丑')) {$star_hour = '쇄(衰)';}
if (($my_day_h == '壬') && ($my_hour_e == '寅')) {$star_hour = '병(病)';}
if (($my_day_h == '壬') && ($my_hour_e == '卯')) {$star_hour = '사(死)';}
if (($my_day_h == '壬') && ($my_hour_e == '辰')) {$star_hour = '묘(墓)';}
if (($my_day_h == '壬') && ($my_hour_e == '巳')) {$star_hour = '절(絶)';}
if (($my_day_h == '壬') && ($my_hour_e == '午')) {$star_hour = '태(胎)';}
if (($my_day_h == '壬') && ($my_hour_e == '未')) {$star_hour = '양(養)';}
####################################################################
if (($my_day_h == '癸') && ($my_year_e == '卯')) {$star_year = '장생(長生)';}
if (($my_day_h == '癸') && ($my_year_e == '寅')) {$star_year = '목욕(沐浴)';}
if (($my_day_h == '癸') && ($my_year_e == '丑')) {$star_year = '관대(冠帶)';}
if (($my_day_h == '癸') && ($my_year_e == '子')) {$star_year = '건록(建祿)';}
if (($my_day_h == '癸') && ($my_year_e == '亥')) {$star_year = '제왕(帝旺)';}
if (($my_day_h == '癸') && ($my_year_e == '戌')) {$star_year = '쇄(衰)';}
if (($my_day_h == '癸') && ($my_year_e == '酉')) {$star_year = '병(病)';}
if (($my_day_h == '癸') && ($my_year_e == '申')) {$star_year = '사(死)';}
if (($my_day_h == '癸') && ($my_year_e == '未')) {$star_year = '묘(墓)';}
if (($my_day_h == '癸') && ($my_year_e == '午')) {$star_year = '절(絶)';}
if (($my_day_h == '癸') && ($my_year_e == '巳')) {$star_year = '태(胎)';}
if (($my_day_h == '癸') && ($my_year_e == '辰')) {$star_year = '양(養)';}

if (($my_day_h == '癸') && ($my_month_e == '卯')) {$star_month = '장생(長生)';}
if (($my_day_h == '癸') && ($my_month_e == '寅')) {$star_month = '목욕(沐浴)';}
if (($my_day_h == '癸') && ($my_month_e == '丑')) {$star_month = '관대(冠帶)';}
if (($my_day_h == '癸') && ($my_month_e == '子')) {$star_month = '건록(建祿)';}
if (($my_day_h == '癸') && ($my_month_e == '亥')) {$star_month = '제왕(帝旺)';}
if (($my_day_h == '癸') && ($my_month_e == '戌')) {$star_month = '쇄(衰)';}
if (($my_day_h == '癸') && ($my_month_e == '酉')) {$star_month = '병(病)';}
if (($my_day_h == '癸') && ($my_month_e == '申')) {$star_month = '사(死)';}
if (($my_day_h == '癸') && ($my_month_e == '未')) {$star_month = '묘(墓)';}
if (($my_day_h == '癸') && ($my_month_e == '午')) {$star_month = '절(絶)';}
if (($my_day_h == '癸') && ($my_month_e == '巳')) {$star_month = '태(胎)';}
if (($my_day_h == '癸') && ($my_month_e == '辰')) {$star_month = '양(養)';}

if (($my_day_h == '癸') && ($my_day_e == '卯')) {$star_day = '장생(長生)';}
if (($my_day_h == '癸') && ($my_day_e == '寅')) {$star_day = '목욕(沐浴)';}
if (($my_day_h == '癸') && ($my_day_e == '丑')) {$star_day = '관대(冠帶)';}
if (($my_day_h == '癸') && ($my_day_e == '子')) {$star_day = '건록(建祿)';}
if (($my_day_h == '癸') && ($my_day_e == '亥')) {$star_day = '제왕(帝旺)';}
if (($my_day_h == '癸') && ($my_day_e == '戌')) {$star_day = '쇄(衰)';}
if (($my_day_h == '癸') && ($my_day_e == '酉')) {$star_day = '병(病)';}
if (($my_day_h == '癸') && ($my_day_e == '申')) {$star_day = '사(死)';}
if (($my_day_h == '癸') && ($my_day_e == '未')) {$star_day = '묘(墓)';}
if (($my_day_h == '癸') && ($my_day_e == '午')) {$star_day = '절(絶)';}
if (($my_day_h == '癸') && ($my_day_e == '巳')) {$star_day = '태(胎)';}
if (($my_day_h == '癸') && ($my_day_e == '辰')) {$star_day = '양(養)';}

if (($my_day_h == '癸') && ($my_hour_e == '卯')) {$star_hour = '장생(長生)';}
if (($my_day_h == '癸') && ($my_hour_e == '寅')) {$star_hour = '목욕(沐浴)';}
if (($my_day_h == '癸') && ($my_hour_e == '丑')) {$star_hour = '관대(冠帶)';}
if (($my_day_h == '癸') && ($my_hour_e == '子')) {$star_hour = '건록(建祿)';}
if (($my_day_h == '癸') && ($my_hour_e == '亥')) {$star_hour = '제왕(帝旺)';}
if (($my_day_h == '癸') && ($my_hour_e == '戌')) {$star_hour = '쇄(衰)';}
if (($my_day_h == '癸') && ($my_hour_e == '酉')) {$star_hour = '병(病)';}
if (($my_day_h == '癸') && ($my_hour_e == '申')) {$star_hour = '사(死)';}
if (($my_day_h == '癸') && ($my_hour_e == '未')) {$star_hour = '묘(墓)';}
if (($my_day_h == '癸') && ($my_hour_e == '午')) {$star_hour = '절(絶)';}
if (($my_day_h == '癸') && ($my_hour_e == '巳')) {$star_hour = '태(胎)';}
if (($my_day_h == '癸') && ($my_hour_e == '辰')) {$star_hour = '양(養)';}


#########################################################################


?>
