
<?
##############################################################################################12운성 산출
if (($your_day_h == '甲') && ($your_year_e == '亥')) {$your_star_year = '장생(長生)';}
if (($your_day_h == '甲') && ($your_year_e == '子')) {$your_star_year = '목욕(沐浴)';}
if (($your_day_h == '甲') && ($your_year_e == '丑')) {$your_star_year = '관대(冠帶)';}
if (($your_day_h == '甲') && ($your_year_e == '寅')) {$your_star_year = '건록(建祿)';}
if (($your_day_h == '甲') && ($your_year_e == '卯')) {$your_star_year = '제왕(帝旺)';}
if (($your_day_h == '甲') && ($your_year_e == '辰')) {$your_star_year = '쇄(衰)';}
if (($your_day_h == '甲') && ($your_year_e == '巳')) {$your_star_year = '병(病)';}
if (($your_day_h == '甲') && ($your_year_e == '午')) {$your_star_year = '사(死)';}
if (($your_day_h == '甲') && ($your_year_e == '未')) {$your_star_year = '묘(墓)';}
if (($your_day_h == '甲') && ($your_year_e == '申')) {$your_star_year = '절(絶)';}
if (($your_day_h == '甲') && ($your_year_e == '酉')) {$your_star_year = '태(胎)';}
if (($your_day_h == '甲') && ($your_year_e == '戌')) {$your_star_year = '양(養)';}

if (($your_day_h == '甲') && ($your_month_e == '亥')) {$your_star_month = '장생(長生)';}
if (($your_day_h == '甲') && ($your_month_e == '子')) {$your_star_month = '목욕(沐浴)';}
if (($your_day_h == '甲') && ($your_month_e == '丑')) {$your_star_month = '관대(冠帶)';}
if (($your_day_h == '甲') && ($your_month_e == '寅')) {$your_star_month = '건록(建祿)';}
if (($your_day_h == '甲') && ($your_month_e == '卯')) {$your_star_month = '제왕(帝旺)';}
if (($your_day_h == '甲') && ($your_month_e == '辰')) {$your_star_month = '쇄(衰)';}
if (($your_day_h == '甲') && ($your_month_e == '巳')) {$your_star_month = '병(病)';}
if (($your_day_h == '甲') && ($your_month_e == '午')) {$your_star_month = '사(死)';}
if (($your_day_h == '甲') && ($your_month_e == '未')) {$your_star_month = '묘(墓)';}
if (($your_day_h == '甲') && ($your_month_e == '申')) {$your_star_month = '절(絶)';}
if (($your_day_h == '甲') && ($your_month_e == '酉')) {$your_star_month = '태(胎)';}
if (($your_day_h == '甲') && ($your_month_e == '戌')) {$your_star_month = '양(養)';}

if (($your_day_h == '甲') && ($your_day_e == '亥')) {$your_star_day = '장생(長生)';}
if (($your_day_h == '甲') && ($your_day_e == '子')) {$your_star_day = '목욕(沐浴)';}
if (($your_day_h == '甲') && ($your_day_e == '丑')) {$your_star_day = '관대(冠帶)';}
if (($your_day_h == '甲') && ($your_day_e == '寅')) {$your_star_day = '건록(建祿)';}
if (($your_day_h == '甲') && ($your_day_e == '卯')) {$your_star_day = '제왕(帝旺)';}
if (($your_day_h == '甲') && ($your_day_e == '辰')) {$your_star_day = '쇄(衰)';}
if (($your_day_h == '甲') && ($your_day_e == '巳')) {$your_star_day = '병(病)';}
if (($your_day_h == '甲') && ($your_day_e == '午')) {$your_star_day = '사(死)';}
if (($your_day_h == '甲') && ($your_day_e == '未')) {$your_star_day = '묘(墓)';}
if (($your_day_h == '甲') && ($your_day_e == '申')) {$your_star_day = '절(絶)';}
if (($your_day_h == '甲') && ($your_day_e == '酉')) {$your_star_day = '태(胎)';}
if (($your_day_h == '甲') && ($your_day_e == '戌')) {$your_star_day = '양(養)';}

if (($your_day_h == '甲') && ($your_hour_e == '亥')) {$your_star_hour = '장생(長生)';}
if (($your_day_h == '甲') && ($your_hour_e == '子')) {$your_star_hour = '목욕(沐浴)';}
if (($your_day_h == '甲') && ($your_hour_e == '丑')) {$your_star_hour = '관대(冠帶)';}
if (($your_day_h == '甲') && ($your_hour_e == '寅')) {$your_star_hour = '건록(建祿)';}
if (($your_day_h == '甲') && ($your_hour_e == '卯')) {$your_star_hour = '제왕(帝旺)';}
if (($your_day_h == '甲') && ($your_hour_e == '辰')) {$your_star_hour = '쇄(衰)';}
if (($your_day_h == '甲') && ($your_hour_e == '巳')) {$your_star_hour = '병(病)';}
if (($your_day_h == '甲') && ($your_hour_e == '午')) {$your_star_hour = '사(死)';}
if (($your_day_h == '甲') && ($your_hour_e == '未')) {$your_star_hour = '묘(墓)';}
if (($your_day_h == '甲') && ($your_hour_e == '申')) {$your_star_hour = '절(絶)';}
if (($your_day_h == '甲') && ($your_hour_e == '酉')) {$your_star_hour = '태(胎)';}
if (($your_day_h == '甲') && ($your_hour_e == '戌')) {$your_star_hour = '양(養)';}
##################################################################
if (($your_day_h == '乙') && ($your_year_e == '午')) {$your_star_year = '장생(長生)';}
if (($your_day_h == '乙') && ($your_year_e == '巳')) {$your_star_year = '목욕(沐浴)';}
if (($your_day_h == '乙') && ($your_year_e == '辰')) {$your_star_year = '관대(冠帶)';}
if (($your_day_h == '乙') && ($your_year_e == '卯')) {$your_star_year = '건록(建祿)';}
if (($your_day_h == '乙') && ($your_year_e == '寅')) {$your_star_year = '제왕(帝旺)';}
if (($your_day_h == '乙') && ($your_year_e == '丑')) {$your_star_year = '쇄(衰)';}
if (($your_day_h == '乙') && ($your_year_e == '子')) {$your_star_year = '병(病)';}
if (($your_day_h == '乙') && ($your_year_e == '亥')) {$your_star_year = '사(死)';}
if (($your_day_h == '乙') && ($your_year_e == '戌')) {$your_star_year = '묘(墓)';}
if (($your_day_h == '乙') && ($your_year_e == '酉')) {$your_star_year = '절(絶)';}
if (($your_day_h == '乙') && ($your_year_e == '申')) {$your_star_year = '태(胎)';}
if (($your_day_h == '乙') && ($your_year_e == '未')) {$your_star_year = '양(養)';}

if (($your_day_h == '乙') && ($your_month_e == '午')) {$your_star_month = '장생(長生)';}
if (($your_day_h == '乙') && ($your_month_e == '巳')) {$your_star_month = '목욕(沐浴)';}
if (($your_day_h == '乙') && ($your_month_e == '辰')) {$your_star_month = '관대(冠帶)';}
if (($your_day_h == '乙') && ($your_month_e == '卯')) {$your_star_month = '건록(建祿)';}
if (($your_day_h == '乙') && ($your_month_e == '寅')) {$your_star_month = '제왕(帝旺)';}
if (($your_day_h == '乙') && ($your_month_e == '丑')) {$your_star_month = '쇄(衰)';}
if (($your_day_h == '乙') && ($your_month_e == '子')) {$your_star_month = '병(病)';}
if (($your_day_h == '乙') && ($your_month_e == '亥')) {$your_star_month = '사(死)';}
if (($your_day_h == '乙') && ($your_month_e == '戌')) {$your_star_month = '묘(墓)';}
if (($your_day_h == '乙') && ($your_month_e == '酉')) {$your_star_month = '절(絶)';}
if (($your_day_h == '乙') && ($your_month_e == '申')) {$your_star_month = '태(胎)';}
if (($your_day_h == '乙') && ($your_month_e == '未')) {$your_star_month = '양(養)';}

if (($your_day_h == '乙') && ($your_day_e == '午')) {$your_star_day = '장생(長生)';}
if (($your_day_h == '乙') && ($your_day_e == '巳')) {$your_star_day = '목욕(沐浴)';}
if (($your_day_h == '乙') && ($your_day_e == '辰')) {$your_star_day = '관대(冠帶)';}
if (($your_day_h == '乙') && ($your_day_e == '卯')) {$your_star_day = '건록(建祿)';}
if (($your_day_h == '乙') && ($your_day_e == '寅')) {$your_star_day = '제왕(帝旺)';}
if (($your_day_h == '乙') && ($your_day_e == '丑')) {$your_star_day = '쇄(衰)';}
if (($your_day_h == '乙') && ($your_day_e == '子')) {$your_star_day = '병(病)';}
if (($your_day_h == '乙') && ($your_day_e == '亥')) {$your_star_day = '사(死)';}
if (($your_day_h == '乙') && ($your_day_e == '戌')) {$your_star_day = '묘(墓)';}
if (($your_day_h == '乙') && ($your_day_e == '酉')) {$your_star_day = '절(絶)';}
if (($your_day_h == '乙') && ($your_day_e == '申')) {$your_star_day = '태(胎)';}
if (($your_day_h == '乙') && ($your_day_e == '未')) {$your_star_day = '양(養)';}

if (($your_day_h == '乙') && ($your_hour_e == '午')) {$your_star_hour = '장생(長生)';}
if (($your_day_h == '乙') && ($your_hour_e == '巳')) {$your_star_hour = '목욕(沐浴)';}
if (($your_day_h == '乙') && ($your_hour_e == '辰')) {$your_star_hour = '관대(冠帶)';}
if (($your_day_h == '乙') && ($your_hour_e == '卯')) {$your_star_hour = '건록(建祿)';}
if (($your_day_h == '乙') && ($your_hour_e == '寅')) {$your_star_hour = '제왕(帝旺)';}
if (($your_day_h == '乙') && ($your_hour_e == '丑')) {$your_star_hour = '쇄(衰)';}
if (($your_day_h == '乙') && ($your_hour_e == '子')) {$your_star_hour = '병(病)';}
if (($your_day_h == '乙') && ($your_hour_e == '亥')) {$your_star_hour = '사(死)';}
if (($your_day_h == '乙') && ($your_hour_e == '戌')) {$your_star_hour = '묘(墓)';}
if (($your_day_h == '乙') && ($your_hour_e == '酉')) {$your_star_hour = '절(絶)';}
if (($your_day_h == '乙') && ($your_hour_e == '申')) {$your_star_hour = '태(胎)';}
if (($your_day_h == '乙') && ($your_hour_e == '未')) {$your_star_hour = '양(養)';}
#####################################################################
if (($your_day_h == '丙') && ($your_year_e == '寅')) {$your_star_year = '장생(長生)';}
if (($your_day_h == '丙') && ($your_year_e == '卯')) {$your_star_year = '목욕(沐浴)';}
if (($your_day_h == '丙') && ($your_year_e == '辰')) {$your_star_year = '관대(冠帶)';}
if (($your_day_h == '丙') && ($your_year_e == '巳')) {$your_star_year = '건록(建祿)';}
if (($your_day_h == '丙') && ($your_year_e == '午')) {$your_star_year = '제왕(帝旺)';}
if (($your_day_h == '丙') && ($your_year_e == '未')) {$your_star_year = '쇄(衰)';}
if (($your_day_h == '丙') && ($your_year_e == '申')) {$your_star_year = '병(病)';}
if (($your_day_h == '丙') && ($your_year_e == '酉')) {$your_star_year = '사(死)';}
if (($your_day_h == '丙') && ($your_year_e == '戌')) {$your_star_year = '묘(墓)';}
if (($your_day_h == '丙') && ($your_year_e == '亥')) {$your_star_year = '절(絶)';}
if (($your_day_h == '丙') && ($your_year_e == '子')) {$your_star_year = '태(胎)';}
if (($your_day_h == '丙') && ($your_year_e == '丑')) {$your_star_year = '양(養)';}

if (($your_day_h == '丙') && ($your_month_e == '寅')) {$your_star_month = '장생(長生)';}
if (($your_day_h == '丙') && ($your_month_e == '卯')) {$your_star_month = '목욕(沐浴)';}
if (($your_day_h == '丙') && ($your_month_e == '辰')) {$your_star_month = '관대(冠帶)';}
if (($your_day_h == '丙') && ($your_month_e == '巳')) {$your_star_month = '건록(建祿)';}
if (($your_day_h == '丙') && ($your_month_e == '午')) {$your_star_month = '제왕(帝旺)';}
if (($your_day_h == '丙') && ($your_month_e == '未')) {$your_star_month = '쇄(衰)';}
if (($your_day_h == '丙') && ($your_month_e == '申')) {$your_star_month = '병(病)';}
if (($your_day_h == '丙') && ($your_month_e == '酉')) {$your_star_month = '사(死)';}
if (($your_day_h == '丙') && ($your_month_e == '戌')) {$your_star_month = '묘(墓)';}
if (($your_day_h == '丙') && ($your_month_e == '亥')) {$your_star_month = '절(絶)';}
if (($your_day_h == '丙') && ($your_month_e == '子')) {$your_star_month = '태(胎)';}
if (($your_day_h == '丙') && ($your_month_e == '丑')) {$your_star_month = '양(養)';}

if (($your_day_h == '丙') && ($your_day_e == '寅')) {$your_star_day = '장생(長生)';}
if (($your_day_h == '丙') && ($your_day_e == '卯')) {$your_star_day = '목욕(沐浴)';}
if (($your_day_h == '丙') && ($your_day_e == '辰')) {$your_star_day = '관대(冠帶)';}
if (($your_day_h == '丙') && ($your_day_e == '巳')) {$your_star_day = '건록(建祿)';}
if (($your_day_h == '丙') && ($your_day_e == '午')) {$your_star_day = '제왕(帝旺)';}
if (($your_day_h == '丙') && ($your_day_e == '未')) {$your_star_day = '쇄(衰)';}
if (($your_day_h == '丙') && ($your_day_e == '申')) {$your_star_day = '병(病)';}
if (($your_day_h == '丙') && ($your_day_e == '酉')) {$your_star_day = '사(死)';}
if (($your_day_h == '丙') && ($your_day_e == '戌')) {$your_star_day = '묘(墓)';}
if (($your_day_h == '丙') && ($your_day_e == '亥')) {$your_star_day = '절(絶)';}
if (($your_day_h == '丙') && ($your_day_e == '子')) {$your_star_day = '태(胎)';}
if (($your_day_h == '丙') && ($your_day_e == '丑')) {$your_star_day = '양(養)';}

if (($your_day_h == '丙') && ($your_hour_e == '寅')) {$your_star_hour = '장생(長生)';}
if (($your_day_h == '丙') && ($your_hour_e == '卯')) {$your_star_hour = '목욕(沐浴)';}
if (($your_day_h == '丙') && ($your_hour_e == '辰')) {$your_star_hour = '관대(冠帶)';}
if (($your_day_h == '丙') && ($your_hour_e == '巳')) {$your_star_hour = '건록(建祿)';}
if (($your_day_h == '丙') && ($your_hour_e == '午')) {$your_star_hour = '제왕(帝旺)';}
if (($your_day_h == '丙') && ($your_hour_e == '未')) {$your_star_hour = '쇄(衰)';}
if (($your_day_h == '丙') && ($your_hour_e == '申')) {$your_star_hour = '병(病)';}
if (($your_day_h == '丙') && ($your_hour_e == '酉')) {$your_star_hour = '사(死)';}
if (($your_day_h == '丙') && ($your_hour_e == '戌')) {$your_star_hour = '묘(墓)';}
if (($your_day_h == '丙') && ($your_hour_e == '亥')) {$your_star_hour = '절(絶)';}
if (($your_day_h == '丙') && ($your_hour_e == '子')) {$your_star_hour = '태(胎)';}
if (($your_day_h == '丙') && ($your_hour_e == '丑')) {$your_star_hour = '양(養)';}
######################################################################
if (($your_day_h == '丁') && ($your_year_e == '酉')) {$your_star_year = '장생(長生)';}
if (($your_day_h == '丁') && ($your_year_e == '申')) {$your_star_year = '목욕(沐浴)';}
if (($your_day_h == '丁') && ($your_year_e == '未')) {$your_star_year = '관대(冠帶)';}
if (($your_day_h == '丁') && ($your_year_e == '午')) {$your_star_year = '건록(建祿)';}
if (($your_day_h == '丁') && ($your_year_e == '巳')) {$your_star_year = '제왕(帝旺)';}
if (($your_day_h == '丁') && ($your_year_e == '辰')) {$your_star_year = '쇄(衰)';}
if (($your_day_h == '丁') && ($your_year_e == '卯')) {$your_star_year = '병(病)';}
if (($your_day_h == '丁') && ($your_year_e == '寅')) {$your_star_year = '사(死)';}
if (($your_day_h == '丁') && ($your_year_e == '丑')) {$your_star_year = '묘(墓)';}
if (($your_day_h == '丁') && ($your_year_e == '子')) {$your_star_year = '절(絶)';}
if (($your_day_h == '丁') && ($your_year_e == '亥')) {$your_star_year = '태(胎)';}
if (($your_day_h == '丁') && ($your_year_e == '戌')) {$your_star_year = '양(養)';}

if (($your_day_h == '丁') && ($your_month_e == '酉')) {$your_star_month = '장생(長生)';}
if (($your_day_h == '丁') && ($your_month_e == '申')) {$your_star_month = '목욕(沐浴)';}
if (($your_day_h == '丁') && ($your_month_e == '未')) {$your_star_month = '관대(冠帶)';}
if (($your_day_h == '丁') && ($your_month_e == '午')) {$your_star_month = '건록(建祿)';}
if (($your_day_h == '丁') && ($your_month_e == '巳')) {$your_star_month = '제왕(帝旺)';}
if (($your_day_h == '丁') && ($your_month_e == '辰')) {$your_star_month = '쇄(衰)';}
if (($your_day_h == '丁') && ($your_month_e == '卯')) {$your_star_month = '병(病)';}
if (($your_day_h == '丁') && ($your_month_e == '寅')) {$your_star_month = '사(死)';}
if (($your_day_h == '丁') && ($your_month_e == '丑')) {$your_star_month = '묘(墓)';}
if (($your_day_h == '丁') && ($your_month_e == '子')) {$your_star_month = '절(絶)';}
if (($your_day_h == '丁') && ($your_month_e == '亥')) {$your_star_month = '태(胎)';}
if (($your_day_h == '丁') && ($your_month_e == '戌')) {$your_star_month = '양(養)';}

if (($your_day_h == '丁') && ($your_day_e == '酉')) {$your_star_day = '장생(長生)';}
if (($your_day_h == '丁') && ($your_day_e == '申')) {$your_star_day = '목욕(沐浴)';}
if (($your_day_h == '丁') && ($your_day_e == '未')) {$your_star_day = '관대(冠帶)';}
if (($your_day_h == '丁') && ($your_day_e == '午')) {$your_star_day = '건록(建祿)';}
if (($your_day_h == '丁') && ($your_day_e == '巳')) {$your_star_day = '제왕(帝旺)';}
if (($your_day_h == '丁') && ($your_day_e == '辰')) {$your_star_day = '쇄(衰)';}
if (($your_day_h == '丁') && ($your_day_e == '卯')) {$your_star_day = '병(病)';}
if (($your_day_h == '丁') && ($your_day_e == '寅')) {$your_star_day = '사(死)';}
if (($your_day_h == '丁') && ($your_day_e == '丑')) {$your_star_day = '묘(墓)';}
if (($your_day_h == '丁') && ($your_day_e == '子')) {$your_star_day = '절(絶)';}
if (($your_day_h == '丁') && ($your_day_e == '亥')) {$your_star_day = '태(胎)';}
if (($your_day_h == '丁') && ($your_day_e == '戌')) {$your_star_day = '양(養)';}

if (($your_day_h == '丁') && ($your_hour_e == '酉')) {$your_star_hour = '장생(長生)';}
if (($your_day_h == '丁') && ($your_hour_e == '申')) {$your_star_hour = '목욕(沐浴)';}
if (($your_day_h == '丁') && ($your_hour_e == '未')) {$your_star_hour = '관대(冠帶)';}
if (($your_day_h == '丁') && ($your_hour_e == '午')) {$your_star_hour = '건록(建祿)';}
if (($your_day_h == '丁') && ($your_hour_e == '巳')) {$your_star_hour = '제왕(帝旺)';}
if (($your_day_h == '丁') && ($your_hour_e == '辰')) {$your_star_hour = '쇄(衰)';}
if (($your_day_h == '丁') && ($your_hour_e == '卯')) {$your_star_hour = '병(病)';}
if (($your_day_h == '丁') && ($your_hour_e == '寅')) {$your_star_hour = '사(死)';}
if (($your_day_h == '丁') && ($your_hour_e == '丑')) {$your_star_hour = '묘(墓)';}
if (($your_day_h == '丁') && ($your_hour_e == '子')) {$your_star_hour = '절(絶)';}
if (($your_day_h == '丁') && ($your_hour_e == '亥')) {$your_star_hour = '태(胎)';}
if (($your_day_h == '丁') && ($your_hour_e == '戌')) {$your_star_hour = '양(養)';}
###########################################################################
if (($your_day_h == '戊') && ($your_year_e == '寅')) {$your_star_year = '장생(長生)';}
if (($your_day_h == '戊') && ($your_year_e == '卯')) {$your_star_year = '목욕(沐浴)';}
if (($your_day_h == '戊') && ($your_year_e == '辰')) {$your_star_year = '관대(冠帶)';}
if (($your_day_h == '戊') && ($your_year_e == '巳')) {$your_star_year = '건록(建祿)';}
if (($your_day_h == '戊') && ($your_year_e == '午')) {$your_star_year = '제왕(帝旺)';}
if (($your_day_h == '戊') && ($your_year_e == '未')) {$your_star_year = '쇄(衰)';}
if (($your_day_h == '戊') && ($your_year_e == '申')) {$your_star_year = '병(病)';}
if (($your_day_h == '戊') && ($your_year_e == '酉')) {$your_star_year = '사(死)';}
if (($your_day_h == '戊') && ($your_year_e == '戌')) {$your_star_year = '묘(墓)';}
if (($your_day_h == '戊') && ($your_year_e == '亥')) {$your_star_year = '절(絶)';}
if (($your_day_h == '戊') && ($your_year_e == '子')) {$your_star_year = '태(胎)';}
if (($your_day_h == '戊') && ($your_year_e == '丑')) {$your_star_year = '양(養)';}

if (($your_day_h == '戊') && ($your_month_e == '寅')) {$your_star_month = '장생(長生)';}
if (($your_day_h == '戊') && ($your_month_e == '卯')) {$your_star_month = '목욕(沐浴)';}
if (($your_day_h == '戊') && ($your_month_e == '辰')) {$your_star_month = '관대(冠帶)';}
if (($your_day_h == '戊') && ($your_month_e == '巳')) {$your_star_month = '건록(建祿)';}
if (($your_day_h == '戊') && ($your_month_e == '午')) {$your_star_month = '제왕(帝旺)';}
if (($your_day_h == '戊') && ($your_month_e == '未')) {$your_star_month = '쇄(衰)';}
if (($your_day_h == '戊') && ($your_month_e == '申')) {$your_star_month = '병(病)';}
if (($your_day_h == '戊') && ($your_month_e == '酉')) {$your_star_month = '사(死)';}
if (($your_day_h == '戊') && ($your_month_e == '戌')) {$your_star_month = '묘(墓)';}
if (($your_day_h == '戊') && ($your_month_e == '亥')) {$your_star_month = '절(絶)';}
if (($your_day_h == '戊') && ($your_month_e == '子')) {$your_star_month = '태(胎)';}
if (($your_day_h == '戊') && ($your_month_e == '丑')) {$your_star_month = '양(養)';}

if (($your_day_h == '戊') && ($your_day_e == '寅')) {$your_star_day = '장생(長生)';}
if (($your_day_h == '戊') && ($your_day_e == '卯')) {$your_star_day = '목욕(沐浴)';}
if (($your_day_h == '戊') && ($your_day_e == '辰')) {$your_star_day = '관대(冠帶)';}
if (($your_day_h == '戊') && ($your_day_e == '巳')) {$your_star_day = '건록(建祿)';}
if (($your_day_h == '戊') && ($your_day_e == '午')) {$your_star_day = '제왕(帝旺)';}
if (($your_day_h == '戊') && ($your_day_e == '未')) {$your_star_day = '쇄(衰)';}
if (($your_day_h == '戊') && ($your_day_e == '申')) {$your_star_day = '병(病)';}
if (($your_day_h == '戊') && ($your_day_e == '酉')) {$your_star_day = '사(死)';}
if (($your_day_h == '戊') && ($your_day_e == '戌')) {$your_star_day = '묘(墓)';}
if (($your_day_h == '戊') && ($your_day_e == '亥')) {$your_star_day = '절(絶)';}
if (($your_day_h == '戊') && ($your_day_e == '子')) {$your_star_day = '태(胎)';}
if (($your_day_h == '戊') && ($your_day_e == '丑')) {$your_star_day = '양(養)';}

if (($your_day_h == '戊') && ($your_hour_e == '寅')) {$your_star_hour = '장생(長生)';}
if (($your_day_h == '戊') && ($your_hour_e == '卯')) {$your_star_hour = '목욕(沐浴)';}
if (($your_day_h == '戊') && ($your_hour_e == '辰')) {$your_star_hour = '관대(冠帶)';}
if (($your_day_h == '戊') && ($your_hour_e == '巳')) {$your_star_hour = '건록(建祿)';}
if (($your_day_h == '戊') && ($your_hour_e == '午')) {$your_star_hour = '제왕(帝旺)';}
if (($your_day_h == '戊') && ($your_hour_e == '未')) {$your_star_hour = '쇄(衰)';}
if (($your_day_h == '戊') && ($your_hour_e == '申')) {$your_star_hour = '병(病)';}
if (($your_day_h == '戊') && ($your_hour_e == '酉')) {$your_star_hour = '사(死)';}
if (($your_day_h == '戊') && ($your_hour_e == '戌')) {$your_star_hour = '묘(墓)';}
if (($your_day_h == '戊') && ($your_hour_e == '亥')) {$your_star_hour = '절(絶)';}
if (($your_day_h == '戊') && ($your_hour_e == '子')) {$your_star_hour = '태(胎)';}
if (($your_day_h == '戊') && ($your_hour_e == '丑')) {$your_star_hour = '양(養)';}
########################################################################
if (($your_day_h == '己') && ($your_year_e == '酉')) {$your_star_year = '장생(長生)';}
if (($your_day_h == '己') && ($your_year_e == '申')) {$your_star_year = '목욕(沐浴)';}
if (($your_day_h == '己') && ($your_year_e == '未')) {$your_star_year = '관대(冠帶)';}
if (($your_day_h == '己') && ($your_year_e == '午')) {$your_star_year = '건록(建祿)';}
if (($your_day_h == '己') && ($your_year_e == '巳')) {$your_star_year = '제왕(帝旺)';}
if (($your_day_h == '己') && ($your_year_e == '辰')) {$your_star_year = '쇄(衰)';}
if (($your_day_h == '己') && ($your_year_e == '卯')) {$your_star_year = '병(病)';}
if (($your_day_h == '己') && ($your_year_e == '寅')) {$your_star_year = '사(死)';}
if (($your_day_h == '己') && ($your_year_e == '丑')) {$your_star_year = '묘(墓)';}
if (($your_day_h == '己') && ($your_year_e == '子')) {$your_star_year = '절(絶)';}
if (($your_day_h == '己') && ($your_year_e == '亥')) {$your_star_year = '태(胎)';}
if (($your_day_h == '己') && ($your_year_e == '戌')) {$your_star_year = '양(養)';}

if (($your_day_h == '己') && ($your_month_e == '酉')) {$your_star_month = '장생(長生)';}
if (($your_day_h == '己') && ($your_month_e == '申')) {$your_star_month = '목욕(沐浴)';}
if (($your_day_h == '己') && ($your_month_e == '未')) {$your_star_month = '관대(冠帶)';}
if (($your_day_h == '己') && ($your_month_e == '午')) {$your_star_month = '건록(建祿)';}
if (($your_day_h == '己') && ($your_month_e == '巳')) {$your_star_month = '제왕(帝旺)';}
if (($your_day_h == '己') && ($your_month_e == '辰')) {$your_star_month = '쇄(衰)';}
if (($your_day_h == '己') && ($your_month_e == '卯')) {$your_star_month = '병(病)';}
if (($your_day_h == '己') && ($your_month_e == '寅')) {$your_star_month = '사(死)';}
if (($your_day_h == '己') && ($your_month_e == '丑')) {$your_star_month = '묘(墓)';}
if (($your_day_h == '己') && ($your_month_e == '子')) {$your_star_month = '절(絶)';}
if (($your_day_h == '己') && ($your_month_e == '亥')) {$your_star_month = '태(胎)';}
if (($your_day_h == '己') && ($your_month_e == '戌')) {$your_star_month = '양(養)';}

if (($your_day_h == '己') && ($your_day_e == '酉')) {$your_star_day = '장생(長生)';}
if (($your_day_h == '己') && ($your_day_e == '申')) {$your_star_day = '목욕(沐浴)';}
if (($your_day_h == '己') && ($your_day_e == '未')) {$your_star_day = '관대(冠帶)';}
if (($your_day_h == '己') && ($your_day_e == '午')) {$your_star_day = '건록(建祿)';}
if (($your_day_h == '己') && ($your_day_e == '巳')) {$your_star_day = '제왕(帝旺)';}
if (($your_day_h == '己') && ($your_day_e == '辰')) {$your_star_day = '쇄(衰)';}
if (($your_day_h == '己') && ($your_day_e == '卯')) {$your_star_day = '병(病)';}
if (($your_day_h == '己') && ($your_day_e == '寅')) {$your_star_day = '사(死)';}
if (($your_day_h == '己') && ($your_day_e == '丑')) {$your_star_day = '묘(墓)';}
if (($your_day_h == '己') && ($your_day_e == '子')) {$your_star_day = '절(絶)';}
if (($your_day_h == '己') && ($your_day_e == '亥')) {$your_star_day = '태(胎)';}
if (($your_day_h == '己') && ($your_day_e == '戌')) {$your_star_day = '양(養)';}

if (($your_day_h == '己') && ($your_hour_e == '酉')) {$your_star_hour = '장생(長生)';}
if (($your_day_h == '己') && ($your_hour_e == '申')) {$your_star_hour = '목욕(沐浴)';}
if (($your_day_h == '己') && ($your_hour_e == '未')) {$your_star_hour = '관대(冠帶)';}
if (($your_day_h == '己') && ($your_hour_e == '午')) {$your_star_hour = '건록(建祿)';}
if (($your_day_h == '己') && ($your_hour_e == '巳')) {$your_star_hour = '제왕(帝旺)';}
if (($your_day_h == '己') && ($your_hour_e == '辰')) {$your_star_hour = '쇄(衰)';}
if (($your_day_h == '己') && ($your_hour_e == '卯')) {$your_star_hour = '병(病)';}
if (($your_day_h == '己') && ($your_hour_e == '寅')) {$your_star_hour = '사(死)';}
if (($your_day_h == '己') && ($your_hour_e == '丑')) {$your_star_hour = '묘(墓)';}
if (($your_day_h == '己') && ($your_hour_e == '子')) {$your_star_hour = '절(絶)';}
if (($your_day_h == '己') && ($your_hour_e == '亥')) {$your_star_hour = '태(胎)';}
if (($your_day_h == '己') && ($your_hour_e == '戌')) {$your_star_hour = '양(養)';}
########################################################################
if (($your_day_h == '庚') && ($your_year_e == '巳')) {$your_star_year = '장생(長生)';}
if (($your_day_h == '庚') && ($your_year_e == '午')) {$your_star_year = '목욕(沐浴)';}
if (($your_day_h == '庚') && ($your_year_e == '未')) {$your_star_year = '관대(冠帶)';}
if (($your_day_h == '庚') && ($your_year_e == '申')) {$your_star_year = '건록(建祿)';}
if (($your_day_h == '庚') && ($your_year_e == '酉')) {$your_star_year = '제왕(帝旺)';}
if (($your_day_h == '庚') && ($your_year_e == '戌')) {$your_star_year = '쇄(衰)';}
if (($your_day_h == '庚') && ($your_year_e == '亥')) {$your_star_year = '병(病)';}
if (($your_day_h == '庚') && ($your_year_e == '子')) {$your_star_year = '사(死)';}
if (($your_day_h == '庚') && ($your_year_e == '丑')) {$your_star_year = '묘(墓)';}
if (($your_day_h == '庚') && ($your_year_e == '寅')) {$your_star_year = '절(絶)';}
if (($your_day_h == '庚') && ($your_year_e == '卯')) {$your_star_year = '태(胎)';}
if (($your_day_h == '庚') && ($your_year_e == '辰')) {$your_star_year = '양(養)';}

if (($your_day_h == '庚') && ($your_month_e == '巳')) {$your_star_month = '장생(長生)';}
if (($your_day_h == '庚') && ($your_month_e == '午')) {$your_star_month = '목욕(沐浴)';}
if (($your_day_h == '庚') && ($your_month_e == '未')) {$your_star_month = '관대(冠帶)';}
if (($your_day_h == '庚') && ($your_month_e == '申')) {$your_star_month = '건록(建祿)';}
if (($your_day_h == '庚') && ($your_month_e == '酉')) {$your_star_month = '제왕(帝旺)';}
if (($your_day_h == '庚') && ($your_month_e == '戌')) {$your_star_month = '쇄(衰)';}
if (($your_day_h == '庚') && ($your_month_e == '亥')) {$your_star_month = '병(病)';}
if (($your_day_h == '庚') && ($your_month_e == '子')) {$your_star_month = '사(死)';}
if (($your_day_h == '庚') && ($your_month_e == '丑')) {$your_star_month = '묘(墓)';}
if (($your_day_h == '庚') && ($your_month_e == '寅')) {$your_star_month = '절(絶)';}
if (($your_day_h == '庚') && ($your_month_e == '卯')) {$your_star_month = '태(胎)';}
if (($your_day_h == '庚') && ($your_month_e == '辰')) {$your_star_month = '양(養)';}

if (($your_day_h == '庚') && ($your_day_e == '巳')) {$your_star_day = '장생(長生)';}
if (($your_day_h == '庚') && ($your_day_e == '午')) {$your_star_day = '목욕(沐浴)';}
if (($your_day_h == '庚') && ($your_day_e == '未')) {$your_star_day = '관대(冠帶)';}
if (($your_day_h == '庚') && ($your_day_e == '申')) {$your_star_day = '건록(建祿)';}
if (($your_day_h == '庚') && ($your_day_e == '酉')) {$your_star_day = '제왕(帝旺)';}
if (($your_day_h == '庚') && ($your_day_e == '戌')) {$your_star_day = '쇄(衰)';}
if (($your_day_h == '庚') && ($your_day_e == '亥')) {$your_star_day = '병(病)';}
if (($your_day_h == '庚') && ($your_day_e == '子')) {$your_star_day = '사(死)';}
if (($your_day_h == '庚') && ($your_day_e == '丑')) {$your_star_day = '묘(墓)';}
if (($your_day_h == '庚') && ($your_day_e == '寅')) {$your_star_day = '절(絶)';}
if (($your_day_h == '庚') && ($your_day_e == '卯')) {$your_star_day = '태(胎)';}
if (($your_day_h == '庚') && ($your_day_e == '辰')) {$your_star_day = '양(養)';}

if (($your_day_h == '庚') && ($your_hour_e == '巳')) {$your_star_hour = '장생(長生)';}
if (($your_day_h == '庚') && ($your_hour_e == '午')) {$your_star_hour = '목욕(沐浴)';}
if (($your_day_h == '庚') && ($your_hour_e == '未')) {$your_star_hour = '관대(冠帶)';}
if (($your_day_h == '庚') && ($your_hour_e == '申')) {$your_star_hour = '건록(建祿)';}
if (($your_day_h == '庚') && ($your_hour_e == '酉')) {$your_star_hour = '제왕(帝旺)';}
if (($your_day_h == '庚') && ($your_hour_e == '戌')) {$your_star_hour = '쇄(衰)';}
if (($your_day_h == '庚') && ($your_hour_e == '亥')) {$your_star_hour = '병(病)';}
if (($your_day_h == '庚') && ($your_hour_e == '子')) {$your_star_hour = '사(死)';}
if (($your_day_h == '庚') && ($your_hour_e == '丑')) {$your_star_hour = '묘(墓)';}
if (($your_day_h == '庚') && ($your_hour_e == '寅')) {$your_star_hour = '절(絶)';}
if (($your_day_h == '庚') && ($your_hour_e == '卯')) {$your_star_hour = '태(胎)';}
if (($your_day_h == '庚') && ($your_hour_e == '辰')) {$your_star_hour = '양(養)';}
########################################################################
if (($your_day_h == '辛') && ($your_year_e == '子')) {$your_star_year = '장생(長生)';}
if (($your_day_h == '辛') && ($your_year_e == '亥')) {$your_star_year = '목욕(沐浴)';}
if (($your_day_h == '辛') && ($your_year_e == '戌')) {$your_star_year = '관대(冠帶)';}
if (($your_day_h == '辛') && ($your_year_e == '酉')) {$your_star_year = '건록(建祿)';}
if (($your_day_h == '辛') && ($your_year_e == '申')) {$your_star_year = '제왕(帝旺)';}
if (($your_day_h == '辛') && ($your_year_e == '未')) {$your_star_year = '쇄(衰)';}
if (($your_day_h == '辛') && ($your_year_e == '午')) {$your_star_year = '병(病)';}
if (($your_day_h == '辛') && ($your_year_e == '巳')) {$your_star_year = '사(死)';}
if (($your_day_h == '辛') && ($your_year_e == '辰')) {$your_star_year = '묘(墓)';}
if (($your_day_h == '辛') && ($your_year_e == '卯')) {$your_star_year = '절(絶)';}
if (($your_day_h == '辛') && ($your_year_e == '寅')) {$your_star_year = '태(胎)';}
if (($your_day_h == '辛') && ($your_year_e == '丑')) {$your_star_year = '양(養)';}

if (($your_day_h == '辛') && ($your_month_e == '子')) {$your_star_month = '장생(長生)';}
if (($your_day_h == '辛') && ($your_month_e == '亥')) {$your_star_month = '목욕(沐浴)';}
if (($your_day_h == '辛') && ($your_month_e == '戌')) {$your_star_month = '관대(冠帶)';}
if (($your_day_h == '辛') && ($your_month_e == '酉')) {$your_star_month = '건록(建祿)';}
if (($your_day_h == '辛') && ($your_month_e == '申')) {$your_star_month = '제왕(帝旺)';}
if (($your_day_h == '辛') && ($your_month_e == '未')) {$your_star_month = '쇄(衰)';}
if (($your_day_h == '辛') && ($your_month_e == '午')) {$your_star_month = '병(病)';}
if (($your_day_h == '辛') && ($your_month_e == '巳')) {$your_star_month = '사(死)';}
if (($your_day_h == '辛') && ($your_month_e == '辰')) {$your_star_month = '묘(墓)';}
if (($your_day_h == '辛') && ($your_month_e == '卯')) {$your_star_month = '절(絶)';}
if (($your_day_h == '辛') && ($your_month_e == '寅')) {$your_star_month = '태(胎)';}
if (($your_day_h == '辛') && ($your_month_e == '丑')) {$your_star_month = '양(養)';}

if (($your_day_h == '辛') && ($your_day_e == '子')) {$your_star_day = '장생(長生)';}
if (($your_day_h == '辛') && ($your_day_e == '亥')) {$your_star_day = '목욕(沐浴)';}
if (($your_day_h == '辛') && ($your_day_e == '戌')) {$your_star_day = '관대(冠帶)';}
if (($your_day_h == '辛') && ($your_day_e == '酉')) {$your_star_day = '건록(建祿)';}
if (($your_day_h == '辛') && ($your_day_e == '申')) {$your_star_day = '제왕(帝旺)';}
if (($your_day_h == '辛') && ($your_day_e == '未')) {$your_star_day = '쇄(衰)';}
if (($your_day_h == '辛') && ($your_day_e == '午')) {$your_star_day = '병(病)';}
if (($your_day_h == '辛') && ($your_day_e == '巳')) {$your_star_day = '사(死)';}
if (($your_day_h == '辛') && ($your_day_e == '辰')) {$your_star_day = '묘(墓)';}
if (($your_day_h == '辛') && ($your_day_e == '卯')) {$your_star_day = '절(絶)';}
if (($your_day_h == '辛') && ($your_day_e == '寅')) {$your_star_day = '태(胎)';}
if (($your_day_h == '辛') && ($your_day_e == '丑')) {$your_star_day = '양(養)';}

if (($your_day_h == '辛') && ($your_hour_e == '子')) {$your_star_hour = '장생(長生)';}
if (($your_day_h == '辛') && ($your_hour_e == '亥')) {$your_star_hour = '목욕(沐浴)';}
if (($your_day_h == '辛') && ($your_hour_e == '戌')) {$your_star_hour = '관대(冠帶)';}
if (($your_day_h == '辛') && ($your_hour_e == '酉')) {$your_star_hour = '건록(建祿)';}
if (($your_day_h == '辛') && ($your_hour_e == '申')) {$your_star_hour = '제왕(帝旺)';}
if (($your_day_h == '辛') && ($your_hour_e == '未')) {$your_star_hour = '쇄(衰)';}
if (($your_day_h == '辛') && ($your_hour_e == '午')) {$your_star_hour = '병(病)';}
if (($your_day_h == '辛') && ($your_hour_e == '巳')) {$your_star_hour = '사(死)';}
if (($your_day_h == '辛') && ($your_hour_e == '辰')) {$your_star_hour = '묘(墓)';}
if (($your_day_h == '辛') && ($your_hour_e == '卯')) {$your_star_hour = '절(絶)';}
if (($your_day_h == '辛') && ($your_hour_e == '寅')) {$your_star_hour = '태(胎)';}
if (($your_day_h == '辛') && ($your_hour_e == '丑')) {$your_star_hour = '양(養)';}
#######################################################################
if (($your_day_h == '壬') && ($your_year_e == '申')) {$your_star_year = '장생(長生)';}
if (($your_day_h == '壬') && ($your_year_e == '酉')) {$your_star_year = '목욕(沐浴)';}
if (($your_day_h == '壬') && ($your_year_e == '戌')) {$your_star_year = '관대(冠帶)';}
if (($your_day_h == '壬') && ($your_year_e == '亥')) {$your_star_year = '건록(建祿)';}
if (($your_day_h == '壬') && ($your_year_e == '子')) {$your_star_year = '제왕(帝旺)';}
if (($your_day_h == '壬') && ($your_year_e == '丑')) {$your_star_year = '쇄(衰)';}
if (($your_day_h == '壬') && ($your_year_e == '寅')) {$your_star_year = '병(病)';}
if (($your_day_h == '壬') && ($your_year_e == '卯')) {$your_star_year = '사(死)';}
if (($your_day_h == '壬') && ($your_year_e == '辰')) {$your_star_year = '묘(墓)';}
if (($your_day_h == '壬') && ($your_year_e == '巳')) {$your_star_year = '절(絶)';}
if (($your_day_h == '壬') && ($your_year_e == '午')) {$your_star_year = '태(胎)';}
if (($your_day_h == '壬') && ($your_year_e == '未')) {$your_star_year = '양(養)';}

if (($your_day_h == '壬') && ($your_month_e == '申')) {$your_star_month = '장생(長生)';}
if (($your_day_h == '壬') && ($your_month_e == '酉')) {$your_star_month = '목욕(沐浴)';}
if (($your_day_h == '壬') && ($your_month_e == '戌')) {$your_star_month = '관대(冠帶)';}
if (($your_day_h == '壬') && ($your_month_e == '亥')) {$your_star_month = '건록(建祿)';}
if (($your_day_h == '壬') && ($your_month_e == '子')) {$your_star_month = '제왕(帝旺)';}
if (($your_day_h == '壬') && ($your_month_e == '丑')) {$your_star_month = '쇄(衰)';}
if (($your_day_h == '壬') && ($your_month_e == '寅')) {$your_star_month = '병(病)';}
if (($your_day_h == '壬') && ($your_month_e == '卯')) {$your_star_month = '사(死)';}
if (($your_day_h == '壬') && ($your_month_e == '辰')) {$your_star_month = '묘(墓)';}
if (($your_day_h == '壬') && ($your_month_e == '巳')) {$your_star_month = '절(絶)';}
if (($your_day_h == '壬') && ($your_month_e == '午')) {$your_star_month = '태(胎)';}
if (($your_day_h == '壬') && ($your_month_e == '未')) {$your_star_month = '양(養)';}

if (($your_day_h == '壬') && ($your_day_e == '申')) {$your_star_day = '장생(長生)';}
if (($your_day_h == '壬') && ($your_day_e == '酉')) {$your_star_day = '목욕(沐浴)';}
if (($your_day_h == '壬') && ($your_day_e == '戌')) {$your_star_day = '관대(冠帶)';}
if (($your_day_h == '壬') && ($your_day_e == '亥')) {$your_star_day = '건록(建祿)';}
if (($your_day_h == '壬') && ($your_day_e == '子')) {$your_star_day = '제왕(帝旺)';}
if (($your_day_h == '壬') && ($your_day_e == '丑')) {$your_star_day = '쇄(衰)';}
if (($your_day_h == '壬') && ($your_day_e == '寅')) {$your_star_day = '병(病)';}
if (($your_day_h == '壬') && ($your_day_e == '卯')) {$your_star_day = '사(死)';}
if (($your_day_h == '壬') && ($your_day_e == '辰')) {$your_star_day = '묘(墓)';}
if (($your_day_h == '壬') && ($your_day_e == '巳')) {$your_star_day = '절(絶)';}
if (($your_day_h == '壬') && ($your_day_e == '午')) {$your_star_day = '태(胎)';}
if (($your_day_h == '壬') && ($your_day_e == '未')) {$your_star_day = '양(養)';}

if (($your_day_h == '壬') && ($your_hour_e == '申')) {$your_star_hour = '장생(長生)';}
if (($your_day_h == '壬') && ($your_hour_e == '酉')) {$your_star_hour = '목욕(沐浴)';}
if (($your_day_h == '壬') && ($your_hour_e == '戌')) {$your_star_hour = '관대(冠帶)';}
if (($your_day_h == '壬') && ($your_hour_e == '亥')) {$your_star_hour = '건록(建祿)';}
if (($your_day_h == '壬') && ($your_hour_e == '子')) {$your_star_hour = '제왕(帝旺)';}
if (($your_day_h == '壬') && ($your_hour_e == '丑')) {$your_star_hour = '쇄(衰)';}
if (($your_day_h == '壬') && ($your_hour_e == '寅')) {$your_star_hour = '병(病)';}
if (($your_day_h == '壬') && ($your_hour_e == '卯')) {$your_star_hour = '사(死)';}
if (($your_day_h == '壬') && ($your_hour_e == '辰')) {$your_star_hour = '묘(墓)';}
if (($your_day_h == '壬') && ($your_hour_e == '巳')) {$your_star_hour = '절(絶)';}
if (($your_day_h == '壬') && ($your_hour_e == '午')) {$your_star_hour = '태(胎)';}
if (($your_day_h == '壬') && ($your_hour_e == '未')) {$your_star_hour = '양(養)';}
####################################################################
if (($your_day_h == '癸') && ($your_year_e == '卯')) {$your_star_year = '장생(長生)';}
if (($your_day_h == '癸') && ($your_year_e == '寅')) {$your_star_year = '목욕(沐浴)';}
if (($your_day_h == '癸') && ($your_year_e == '丑')) {$your_star_year = '관대(冠帶)';}
if (($your_day_h == '癸') && ($your_year_e == '子')) {$your_star_year = '건록(建祿)';}
if (($your_day_h == '癸') && ($your_year_e == '亥')) {$your_star_year = '제왕(帝旺)';}
if (($your_day_h == '癸') && ($your_year_e == '戌')) {$your_star_year = '쇄(衰)';}
if (($your_day_h == '癸') && ($your_year_e == '酉')) {$your_star_year = '병(病)';}
if (($your_day_h == '癸') && ($your_year_e == '申')) {$your_star_year = '사(死)';}
if (($your_day_h == '癸') && ($your_year_e == '未')) {$your_star_year = '묘(墓)';}
if (($your_day_h == '癸') && ($your_year_e == '午')) {$your_star_year = '절(絶)';}
if (($your_day_h == '癸') && ($your_year_e == '巳')) {$your_star_year = '태(胎)';}
if (($your_day_h == '癸') && ($your_year_e == '辰')) {$your_star_year = '양(養)';}

if (($your_day_h == '癸') && ($your_month_e == '卯')) {$your_star_month = '장생(長生)';}
if (($your_day_h == '癸') && ($your_month_e == '寅')) {$your_star_month = '목욕(沐浴)';}
if (($your_day_h == '癸') && ($your_month_e == '丑')) {$your_star_month = '관대(冠帶)';}
if (($your_day_h == '癸') && ($your_month_e == '子')) {$your_star_month = '건록(建祿)';}
if (($your_day_h == '癸') && ($your_month_e == '亥')) {$your_star_month = '제왕(帝旺)';}
if (($your_day_h == '癸') && ($your_month_e == '戌')) {$your_star_month = '쇄(衰)';}
if (($your_day_h == '癸') && ($your_month_e == '酉')) {$your_star_month = '병(病)';}
if (($your_day_h == '癸') && ($your_month_e == '申')) {$your_star_month = '사(死)';}
if (($your_day_h == '癸') && ($your_month_e == '未')) {$your_star_month = '묘(墓)';}
if (($your_day_h == '癸') && ($your_month_e == '午')) {$your_star_month = '절(絶)';}
if (($your_day_h == '癸') && ($your_month_e == '巳')) {$your_star_month = '태(胎)';}
if (($your_day_h == '癸') && ($your_month_e == '辰')) {$your_star_month = '양(養)';}

if (($your_day_h == '癸') && ($your_day_e == '卯')) {$your_star_day = '장생(長生)';}
if (($your_day_h == '癸') && ($your_day_e == '寅')) {$your_star_day = '목욕(沐浴)';}
if (($your_day_h == '癸') && ($your_day_e == '丑')) {$your_star_day = '관대(冠帶)';}
if (($your_day_h == '癸') && ($your_day_e == '子')) {$your_star_day = '건록(建祿)';}
if (($your_day_h == '癸') && ($your_day_e == '亥')) {$your_star_day = '제왕(帝旺)';}
if (($your_day_h == '癸') && ($your_day_e == '戌')) {$your_star_day = '쇄(衰)';}
if (($your_day_h == '癸') && ($your_day_e == '酉')) {$your_star_day = '병(病)';}
if (($your_day_h == '癸') && ($your_day_e == '申')) {$your_star_day = '사(死)';}
if (($your_day_h == '癸') && ($your_day_e == '未')) {$your_star_day = '묘(墓)';}
if (($your_day_h == '癸') && ($your_day_e == '午')) {$your_star_day = '절(絶)';}
if (($your_day_h == '癸') && ($your_day_e == '巳')) {$your_star_day = '태(胎)';}
if (($your_day_h == '癸') && ($your_day_e == '辰')) {$your_star_day = '양(養)';}

if (($your_day_h == '癸') && ($your_hour_e == '卯')) {$your_star_hour = '장생(長生)';}
if (($your_day_h == '癸') && ($your_hour_e == '寅')) {$your_star_hour = '목욕(沐浴)';}
if (($your_day_h == '癸') && ($your_hour_e == '丑')) {$your_star_hour = '관대(冠帶)';}
if (($your_day_h == '癸') && ($your_hour_e == '子')) {$your_star_hour = '건록(建祿)';}
if (($your_day_h == '癸') && ($your_hour_e == '亥')) {$your_star_hour = '제왕(帝旺)';}
if (($your_day_h == '癸') && ($your_hour_e == '戌')) {$your_star_hour = '쇄(衰)';}
if (($your_day_h == '癸') && ($your_hour_e == '酉')) {$your_star_hour = '병(病)';}
if (($your_day_h == '癸') && ($your_hour_e == '申')) {$your_star_hour = '사(死)';}
if (($your_day_h == '癸') && ($your_hour_e == '未')) {$your_star_hour = '묘(墓)';}
if (($your_day_h == '癸') && ($your_hour_e == '午')) {$your_star_hour = '절(絶)';}
if (($your_day_h == '癸') && ($your_hour_e == '巳')) {$your_star_hour = '태(胎)';}
if (($your_day_h == '癸') && ($your_hour_e == '辰')) {$your_star_hour = '양(養)';}


#########################################################################


?>
