<?
    if((($my_month_e_org == "12") && ($my_year_e_org == "11")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "12")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "01")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "02")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "03")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "04")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "05"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "06"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "07"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "08"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "09"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "10")))   {
	$total_to = "10"  ;
    }
     elseif((($my_month_e_org == "12") && ($my_year_e_org == "12")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "01")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "02")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "03")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "04")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "05")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "06"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "07"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "08"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "09"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "10"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "11")))   {
	$total_to = "11"  ;
    }
     elseif((($my_month_e_org == "12") && ($my_year_e_org == "01")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "02")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "03")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "04")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "05")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "06")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "07"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "08"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "09"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "10"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "11"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "12")))   {
	$total_to = "12"  ;
    }
     elseif((($my_month_e_org == "12") && ($my_year_e_org == "02")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "03")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "04")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "05")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "06")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "07")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "08"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "09"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "10"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "11"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "12"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "01")))   {
	$total_to = "01"  ;
    }
     elseif((($my_month_e_org == "12") && ($my_year_e_org == "03")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "04")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "05")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "06")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "07")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "08")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "09"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "10"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "11"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "12"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "01"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "02")))   {
	$total_to = "02"  ;
    }
     elseif((($my_month_e_org == "12") && ($my_year_e_org == "04")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "05")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "06")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "07")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "08")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "09")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "10"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "11"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "12"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "01"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "02"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "03")))   {
	$total_to = "03"  ;
    }
     elseif((($my_month_e_org == "12") && ($my_year_e_org == "05")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "06")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "07")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "08")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "09")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "10")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "11"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "12"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "01"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "02"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "03"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "04")))   {
	$total_to = "04"  ;
    }
     elseif((($my_month_e_org == "12") && ($my_year_e_org == "06")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "07")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "08")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "09")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "10")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "11")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "12"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "01"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "02"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "03"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "04"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "05")))   {
	$total_to = "05"  ;
    }
     elseif((($my_month_e_org == "12") && ($my_year_e_org == "07")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "08")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "09")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "10")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "11")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "12")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "01"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "02"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "03"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "04"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "05"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "06")))   {
	$total_to = "06"  ;
	}
     elseif((($my_month_e_org == "12") && ($my_year_e_org == "08")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "09")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "10")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "11")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "12")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "01")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "02"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "03"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "04"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "05"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "06"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "07")))   {
	$total_to = "07"  ;
    }
     elseif((($my_month_e_org == "12") && ($my_year_e_org == "09")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "10")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "11")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "12")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "01")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "02")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "03"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "04"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "05"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "06"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "07"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "08")))   {
	$total_to = "08"  ;
    }
     elseif((($my_month_e_org == "12") && ($my_year_e_org == "10")) || (( $my_month_e_org == "11") && ( $my_year_e_org == "11")) || (( $my_month_e_org == "10") && ( $my_year_e_org == "12")) || (( $my_month_e_org == "09") && ( $my_year_e_org == "01")) || (( $my_month_e_org == "08") && ( $my_year_e_org == "02")) || (( $my_month_e_org == "07") && ( $my_year_e_org == "03")) || (( $my_month_e_org == "06") && ( $my_year_e_org == "04"))|| (( $my_month_e_org == "05") && ( $my_year_e_org == "05"))|| (( $my_month_e_org == "04") && ( $my_year_e_org == "06"))|| (( $my_month_e_org == "03") && ( $my_year_e_org == "07"))|| (( $my_month_e_org == "02") && ( $my_year_e_org == "08"))|| (( $my_month_e_org == "01") && ( $my_year_e_org == "09")))   {
	$total_to = "09"  ;
    }
?>