<?
 if(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "01"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "02"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "03"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "04"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "05"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "06"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "07"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "08")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "09")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "10")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to == "11"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "12")))   {
	$total_to_01 = "01"  ;
    }
     elseif(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "02"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "03"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "04"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "05"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "06"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "07"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "08"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "09")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "10")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "11")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to== "12"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "01")))   {
	$total_to_01 = "02"  ;
    }
     elseif(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "03"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "04"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "05"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "06"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "07"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "08"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "09"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "10")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "11")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "12")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to == "01"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "02")))   {
	$total_to_01 = "03"  ;
    }
     elseif(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "04"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "05"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "06"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "07"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "08"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "09"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "10"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "11")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "12")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "01")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to == "02"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "03")))   {
	$total_to_01 = "04"  ;
    }
     elseif(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "05"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "06"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "07"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "08"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "09"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "10"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "11"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "12")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "01")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "02")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to == "03"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "04")))   {
	$total_to_01 = "05"  ;
    }
     elseif(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "06"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "07"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "08"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "09"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "10"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "11"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "12"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "01")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "02")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "03")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to == "04"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "05")))   {
	$total_to_01 = "06"  ;
    }
     elseif(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "07"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "08"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "09"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "10"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "11"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "12"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "01"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "02")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "03")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "04")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to == "05"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "06")))   {
	$total_to_01 = "07"  ;
    }
     elseif(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "08"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "09"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "10"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "11"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "12"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "01"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "02"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "03")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "04")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "05")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to == "06"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "07")))   {
	$total_to_01 = "08"  ;
    }
     elseif(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "09"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "10"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "11"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "12"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "01"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "02"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "03"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "04")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "05")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "06")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to == "07"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "08")))   {
	$total_to_01 = "09"  ;
    }
     elseif(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "10"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "11"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "12"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "01"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "02"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "03"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "04"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "05")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "06")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "07")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to == "08"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "09")))   {
	$total_to_01 = "10"  ;
    }
     elseif(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "11"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "12"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "01"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "02"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "03"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "04"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "05"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "06")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "07")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "08")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to == "09"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "10")))   {
	$total_to_01 = "11"  ;
    }
     elseif(((($lunar_day == "01") || ($lunar_day == "13") || ($lunar_day == "25")) && ($total_to == "12"))||((($lunar_day == "12")||($lunar_day == "24")) && ($total_to == "01"))||((( $lunar_day == "11")||( $lunar_day == "23")) && ( $total_to == "02"))||((($lunar_day == "10")||($lunar_day == "22")) && ($total_to == "03"))||((($lunar_day == "09")||( $lunar_day == "21")) && ( $total_to == "04"))||((( $lunar_day == "08")||( $lunar_day == "20")) && ( $total_to == "05"))||((($lunar_day == "07")||($lunar_day == "19")||($lunar_day == "31")) && ( $total_to == "06"))||((($lunar_day == "06")||($lunar_day == "18")||($lunar_day == "30")) && ( $total_to == "07")) || ((( $lunar_day == "05")||( $lunar_day == "17")||( $lunar_day == "29")) && ( $total_to == "08")) || ((($lunar_day == "04")||( $lunar_day == "16")||( $lunar_day == "28")) && ( $total_to == "09")) || ((($lunar_day == "03")||($lunar_day == "15")||($lunar_day == "27")) && ( $total_to == "10"))  || ((($lunar_day == "02")||($lunar_day == "14")||($lunar_day == "26")) && ( $total_to == "11")))   {
	$total_to_01 = "12"  ;
    }
?>